### ISSUE TITLE
api folder

### ISSUE THREAD

**Issue by jacob-grahn** [jacob-grahn/platform-racing-2-server#106]
Is the stuff in http_server/www/api still used for anything? It looks like it integrates with Luna from way back when. Can it be deleted?

**Comment by bls1999** [comment]
I would like to use the award_prize.php api for contests hosted on JV2.  I'll set up the page just like you had it set up on the old JV.

**Comment by bls1999** [comment]
In answer to your question:
 - award_part.php was what was embedded in pr2_prize.swf, which you gave to V4V.  I assume that was also used for awarding parts from contests on JV.
 - calc_exp_points.php appears to be a testing function that doesn't do anything anyone but you would know.
 - is_folding_name_taken.php seems to be a function that checks the db on a user's request.  It still retains its usefulness, but I don't think it's used anywhere.
 - send_code_pm.php seems to send some obscure code to a user from you, permitting that they're from the right IP.  Seems like it was a testing function.

**Comment by bls1999** [comment]
Oh, and most of them call `api_test_ip()` from `http_server/fns/api_fns.php`.  There are two allowed IP addresses in there; presumably, they are either yours or JV's old server/cloudflare IPs.

**Comment by Grovbi** [comment]
send_code_pm.php was used for linking your Luna and PR2 accounts together, I believe. In Luna you'd type the PR2 name you'd want linked to your account, and it would then PM a confirmation code to it that you'd need to add to complete the link.

**Comment by jacob-grahn** [comment]
Ok thanks, I deleted everything but award_part.php.
