### ISSUE TITLE
[Urgent] Need more information re: kicking mechanic

### ISSUE THREAD

**Issue by bls1999** [jacob-grahn/platform-racing-2-server#11]
@jacob-grahn 

If you didn't know, temps can kick staff members.  That's not ideal.

I'd like to nip this in the bud (by adding a restriction on the groups that temps can kick, e.g. if temp mod, only let kick groups less than 2), but I don't know exactly where I'd make this change.  I know it's somewhere in server/pr2_moderation.php, but I really don't want to mess anything up.  I also don't know how I would create an error on-kick.

Any information you could give me would be great.  Thanks for your help!

**Comment by jacob-grahn** [comment]
Is this fixed now with your recent contributions?

**Comment by bls1999** [comment]
@jacob-grahn yes! Thanks!
