### ISSUE TITLE
Add permanent private server for staff team

### ISSUE THREAD

**Issue by bls1999** [jacob-grahn/platform-racing-2-server#112]
@jacob-grahn, could you add a permanent private server for guild ID #183?  This is the PR2 Staff guild.

**Comment by woodenstix** [comment]
Please just stop begging, support @jacob-grahn by buying the private server.

**Comment by jacob-grahn** [comment]
Keep it respectful, @woodenstix. Your thoughts are welcome and appreciated, but remember that it matters how things are said.

**Comment by woodenstix** [comment]
True, I should apologize for my rudeness and not respecting bls1999. I understand that he is trying to do good for this game, but you have to know I don't hate him for doing right, I dislike him because of his personality. I know it's a "bullshit" thing (?) to complain about, but that's my opinion.

**Comment by a7x3** [comment]
To be honest, I'm a student, I dont have the money to spend on a server :')

**Comment by woodenstix** [comment]
[http://prntscr.com/i5isrk](url) [http://prntscr.com/i5fmya](url) @a7x3

**Comment by bls1999** [comment]
Probably should've requested this privately. Oops.

Also, for anyone wondering, this is something about which the staff discussed and decided to ask Jiggmin.

**Comment by a7x3** [comment]
@woodenstix I dont use Kong, I just stick with pr2hub
