### ISSUE TITLE
Issues with Pr2hub

### ISSUE THREAD

**Issue by EternalUF** [jacob-grahn/platform-racing-2-server#113]
I'm going to try to explain this the best I can, for some reason some users are receiving an empty game holder on Pr2hub.com, so far the issue I've found is these users are receiving a 404 Not found error when trying to load:
"http://cdn.jiggmin.com/games/platform-racing-2/platform-racing-2-loader-v13.swf"

And these same users are unable to load on Kongregate also, they receive:
http://prntscr.com/i4zs7g

I'm not exactly sure what's causing this issue, but it seems we are receiving more and more new complaints regarding this daily.

**Comment by Myst1cZ** [comment]
I'm not able to get to pr2hub at all.

**Comment by VipaPR2** [comment]
Yeah I can't load PR2, this is so annoying.

**Comment by jacob-grahn** [comment]
There was a caching issue with the cdn.jiggmin.com domain still going through cloudflare's cache, and the file started expiring from their edge servers. "http://cdn.jiggmin.com/games/platform-racing-2/platform-racing-2-loader-v13.swf" should be loading ok now.

The kong error might be some different file, I'll have to take a look

**Comment by bls1999** [comment]
I think the Kong Data is scripted into and loaded from pr2-v151.swf.  There's some code that detects the domain and does things vault related if it's Kong.

**Comment by VipaPR2** [comment]
Thanks for fixing it Jiggmin!!!!

**Comment by Myst1cZ** [comment]
@jacob-grahn pr2hub still isn't working for me.

**Comment by bls1999** [comment]
@jacob-grahn I wouldn't be too worried since @Myst1cZ is perma-banned and is the only user that has reported this specific problem.  Everyone else affected by the bug has reported that PR2 now works for them.

**Comment by Myst1cZ** [comment]
@bls1999 just because i'm banned doesn't mean i shouldn't be able to go to pr2hub.

**Comment by jacob-grahn** [comment]
Is it working for everyone on kong, too? I just tried it, and it worked there for me.

@Myst1cZ Do you get *anything* from pr2hub.com, or just some kind of error code?

**Comment by Myst1cZ** [comment]
@jacob-grahn I checked the connections when going to pr2hub, screenshot of what i get: https://puu.sh/za2T1.png

**Comment by woodenstix** [comment]
@bls1999 Uhh why would you perm-ban him in the first place if it would change nothing

**Comment by bls1999** [comment]
@woodenstix he was able to access PR2 when we perma-banned him.

**Comment by woodenstix** [comment]
@bls1999 why wouldn't you let him access it? 1 year ban on my main ip feels as perm ban aswell though

**Comment by jacob-grahn** [comment]
@Myst1cZ I'm guessing pr2hub is blocked by your router/isp for some reason, or my hosting company has blacklisted your ip for some reason. Can you get to pr2hub from a proxy?

**Comment by Myst1cZ** [comment]
@jacob-grahn Yes, with proxy it loads perfectly. Also, about IP blacklist, my IP changes everyday.
