### ISSUE TITLE
updating guilds

### ISSUE THREAD

**Issue by EternalUF** [jacob-grahn/platform-racing-2-server#116]
When you go to edit a guild in guild deep info, "error=Could not perform query." is returned, the url is update_guild.php.

**Comment by bls1999** [comment]
I submitted a semi-fix for this.

If you do inspect element on the edit button on guild_deep_info.php and change ?id= to ?guild_id=, it'll give you the appropriate page.  That indicates that the script is working; However, there's another issue with it. #117
