### ISSUE TITLE
413 Request Entity Too Large

### ISSUE THREAD

**Issue by bls1999** [jacob-grahn/platform-racing-2-server#119]
Some users are reporting an error 413 from the new server when trying to upload levels that have lots of content.  Could this be an upload restriction set in place on the server by default?

A user submitted this picture: https://prnt.sc/i58p6a

**Comment by jacob-grahn** [comment]
It looks like the default limit was 1 megabyte. I bumped it up to 5 megabytes, which is hopefully enough!

**Comment by bls1999** [comment]
Great. Thanks!
