### ISSUE TITLE
Platform Racing 2 +0 exp 

### ISSUE THREAD

**Issue by Jmarroqu** [jacob-grahn/platform-racing-2-server#121]
@jacob-grahn Since you're allowing macroing would it be okay if you can get rid of the +0 exp after simming/macroing twice in a sim map? This would help for us not to spam sim/macro maps and not to deal with the Pr2 Staff "Level spamming". Take a look here; http://prntscr.com/i5g9ac Thanks Jiggy :)

**Comment by FearsPR2** [comment]
I agree with Colind. There'd be no need for publishing 9 pages of 6 sim levels each anymore.

**Comment by woodenstix** [comment]
hahaha since macroing is legal now then simming should have no restrictions

**Comment by MagicalBoss** [comment]
Yes! PLEASE FIX THIS ISSUE IT IS VERRY ANNOYING and makes macroing frustrating if I mess it up I gotta restart the process
