### ISSUE TITLE
a7x3 and bls1999 intentionally breaking servers

### ISSUE THREAD

**Issue by woodenstix** [jacob-grahn/platform-racing-2-server#138]
abusing a /give bug to crash servers

nice job staff members

**Comment by bls1999** [comment]
That's not quite what's happening.

a7x3 tried to use the /give command in a race and said the server crashed.  I was puzzled and tried it myself.  Then we moved all the tests to Isabel.

There's no malicious intent.  Don't create drama where there isn't any.

**Comment by woodenstix** [comment]
you created drama with gerrya8 shh

**Comment by Jmarroqu** [comment]
@woodenstix as much as I hate the Pr2 Staff what they did wasn't abusing it they just didn't know it would cause that and stop making useless threads onto here and Close your thread Tyvm ~

**Comment by woodenstix** [comment]
yes i reported a fucking issue and its useless

next thing that will be useless "cant log in on my account, passwords reset" and that would be useless

yeah right

**Comment by a7x3** [comment]
Is this really a thing? I discovered the bug unintentionally, no had the slightest clue that it'd crash the servers, none of us did, so Ben being the one to fix it, he tried it also, which gave proof that indeed it crashes the servers, so after that like above posts, he moved the tests to Isabel, please dont cause drama over this, its a pretty petty matter that will be fixed.

**Comment by bls1999** [comment]
@woodenstix Isabel has a happy hour fam. I'm not sure what motivation you think I'd have to lie about that, but if that's what you want to believe, then I'm not going to try to convince you otherwise.

**Comment by woodenstix** [comment]
> he tried it also

As I mentioned, he could've instantly moved to the **another server**. You clearly ignored my points as you all care about your reputation, I don't because I know I am right and you are not.

> moved the tests to Isabel
At the time I was online you all were talking about it, didn't mention about testing it.

> Isabel has a happy hour
So you only now decided to do it to save yourself? Nice reactions

**Comment by a7x3** [comment]
Ignored your points? I just explained to you what went on and you feel its needed to have a go at staff! My reputation nor Bls's come into this, I tell things as they are regardless of my position, you're pointlessly causing drama here my dude, this will be fixed asap.

**Comment by woodenstix** [comment]
You all pointlessly created drama with Gerrya8 and slandered him, now waiting for your comeback with this fact.

**Comment by bls1999** [comment]
I'm not sure how we get blamed for someone DDoSing the servers after asking to become a moderator and getting denied.

**Comment by a7x3** [comment]
Well considering the countless ban evading and DDosing, obviously things are going to pop up about that, but we are not here to discuss that.

**Comment by woodenstix** [comment]
Proof that he DDoSed? Be sure to add me on discord "ultra mega succ#5397" and you can show me the proof there.

**Comment by bls1999** [comment]
You're not privy to confidential information, sorry.

**Comment by woodenstix** [comment]
See, exactly. You are just lying in front of everyone it's pathetic

**Comment by bls1999** [comment]
See above
"I'm not sure what motivation you think I'd have to lie about that, but if that's what you want to believe, then I'm not going to try to convince you otherwise."

**Comment by woodenstix** [comment]
Okay, explain this: Why do you silence people that clearly state their opinion that they don't like you? By calling you bad words does not mean they should get 1 year bans.

**Comment by bls1999** [comment]
If you wish to discuss staff actions, you can ask in the [Ask a Mod](https://jiggmin2.com/forums/forumdisplay.php?fid=14) forum on JV2.
The staff is done replying to you.  All further inquiries can be directed there.

**Comment by woodenstix** [comment]
@bls1999 what if i'm perm banned on JV2 both of IP and account?

**Comment by bls1999** [comment]
What's your account

**Comment by woodenstix** [comment]
@bls1999 "quit"

**Comment by bls1999** [comment]
Moved you into the banned usergroup that can see Ask a Mod.

**Comment by woodenstix** [comment]
http://prntscr.com/i6txf5 kinda ironic

**Comment by bls1999** [comment]
You've got to log into your forum account in order to access Ask a Mod.

**Comment by woodenstix** [comment]
> Me logging in
Can't log in because it's an IP ban
???

**Comment by bls1999** [comment]
Try now

**Comment by woodenstix** [comment]
http://prntscr.com/i6tzuc

**Comment by bls1999** [comment]
You should be able to access [Ask a Mod](https://jiggmin2.com/forums/forumdisplay.php?fid=14).

**Comment by woodenstix** [comment]
http://prntscr.com/i6u0k2 I should be able? hmm

**Comment by bls1999** [comment]
That's odd. Let me make sure the settings for the banned user group are set properly.

**Comment by woodenstix** [comment]
@bls1999 As I stated it's an IP ban

**Comment by bls1999** [comment]
@woodenstix try again. it should be fixed now

**Comment by woodenstix** [comment]
Finally. Now I can delete these posts because they serve no point anymore

**Comment by jacob-grahn** [comment]
This is not the place for this discussion.
