### ISSUE TITLE
Cannot Connect To New Guild Servers

### ISSUE THREAD

**Issue by LP-PR2** [jacob-grahn/platform-racing-2-server#139]
I bought a guild server and can't even connect to it, it just hangs on Connecting even though the server is up. Another member has also encountered this issue.

**Comment by jacob-grahn** [comment]
Hey LP-PR2, sorry about that. It should be fixed now, let me know if you still have problems. I extended the private server until Feb 5.

**Comment by jacob-grahn** [comment]
I'll wait to close this until I'm sure it's working for everyone.

**Comment by LP-PR2** [comment]
Seems to be working now. Thabks.
