### ISSUE TITLE
Stacking Happy Hours

### ISSUE THREAD

**Issue by Jmarroqu** [jacob-grahn/platform-racing-2-server#140]
I was wondering since we're able to stack 1 day Private Servers and or 30 day Private Server can we do the same for Happy Hours so for example if you buy 10 Happy Hour in a private server after the first happy hour finishes the next 9 will continue.

**Comment by jacob-grahn** [comment]
Thanks, I'll look into this and make sure they stack.

**Comment by jacob-grahn** [comment]
@Jmarroqu 
I reworked the Happy Hour code to get it to stack. Right now the updated code is running on Isabel! If that doesn't crash and burn, then we can release the change to all of the servers.

Thanks!

**Comment by Jmarroqu** [comment]
@jacob-grahn I just bought two Happy Hours on Isabel at :42-43 so we will see if the codes work and if not here's the proof; http://prntscr.com/i86xly

**Comment by Jmarroqu** [comment]
Thanks Jiggmin, the isabel test worked so you can now proceed to update all the Pr2 Servers.
