### ISSUE TITLE
guild_info.php returning inaccurate info

### ISSUE THREAD

**Issue by fourst4r** [jacob-grahn/platform-racing-2-server#142]
If you take a look at [this guild_info.php link](https://pr2hub.com/guild_info.php?getMembers=yes&id=17153) for example, you can see that `member_count` is different from the length of the `members` array.

fiddle to count the members: https://jsfiddle.net/7L8ketjr/

**Comment by bls1999** [comment]
Fixed that one. Admins can correct guild counts now, you just have to report the incorrect ones to us.
