### ISSUE TITLE
Country for IP addresses shows ? in admin tools

### ISSUE THREAD

**Issue by bls1999** [jacob-grahn/platform-racing-2-server#144]
![screen shot 2018-01-28 at 7 41 47 pm](https://user-images.githubusercontent.com/5680237/35489326-8a4ce5a6-0463-11e8-8215-2983256968b1.png)

**Comment by bls1999** [comment]
fixed in #145

**Comment by jacob-grahn** [comment]
Do you know if there are any limits to how often tools.keycdn.com can be queried?

**Comment by bls1999** [comment]
I don't believe so.  I use it for all of my IP things and have never had an issue.  I guess we'll find out 😂 ¯\_(ツ)_/¯
