### ISSUE TITLE
All messages starting with /t (even /test) will start a tournament

### ISSUE THREAD

**Issue by aaaaaa123456789** [jacob-grahn/platform-racing-2-server#15]
https://github.com/jacob-grahn/platform-racing-2-server/blob/cdb42c20ffe42656b553514d0cd0a08184de2b3e/server/Player.php#L267

This check filters all messages starting with `/t`, even stuff like `/test` that shouldn't start a tournament at all. A fix would be `strpos($chat_message, '/tournament') === 0 || strpos($chat_message, '/t ') === 0 || $chat_message === '/t'`.

**Comment by jacob-grahn** [comment]
Yeah, or maybe a regex would be good just to not have such a long 'if' statement
`
else if( preg_match('^\/(tournament|t)$/', $chat_message) ) {
`

**Comment by aaaaaa123456789** [comment]
A regex is cleaner, but slower.
