### ISSUE TITLE
PR2 Idea for Non Simmer/Macro EXP

### ISSUE THREAD

**Issue by FearsPR2** [jacob-grahn/platform-racing-2-server#153]
What if we added a campaign of the week; where that campaign would give bonus exp similar to a happy hour but obviously not doubled exp since happy hours only last one hour.

In order to signify that "x" campaign is the campaign of the week, you could make the server(s) with the campaign of the week have an "@" symbol or something similar. Just an idea to help out non simmers/macroers.

**Comment by woodenstix** [comment]
Because this won't get abused, right?

I think you don't think your ideas through, because sooner later we will have campaign macro bots :joy:

It's going to be worth simming that way then

**Comment by FearsPR2** [comment]
Simming on a campaign map isn't quite as simple as simming on a sim map. Especially since having to actually move through a campaign level is much harder than not having to move at all on a regular sim.

I highly doubt "campaign macro bots" would actually become a thing. Even so, they could just make a rule to not allow simming/macroing on campaign levels and that'd fix the problem.

**Comment by woodenstix** [comment]
>simming/macroing

who cares about simming in a dead game either way

**Comment by FearsPR2** [comment]
@woodenstix again, I don't see you tossing any suggestions for further improving the game, which is what this github is all about, so if you'd kindly keep your ignorant comments to yourself it'd be appreciated.

**Comment by woodenstix** [comment]
who are you calling ignorant? how are you adding more to responding?

so if you'd kindly keep your ignorant comments to yourself it'd be appreciated.

**Comment by jacob-grahn** [comment]
Let's give this a shot! The campaign on Isabel should be giving out double exp.

**Comment by EternalUF** [comment]
This is cool so far! The only issue I see currently is when a server is in Happy hour campaigns give 4x experience, and that’s not including any exp hats.

**Comment by Jmarroqu** [comment]
@jacob-grahn If you set up a macro and my math is very accurate if you get to macro that campaign a min you can get about probably at most 3.5k. 3.5kx60= 210,000/hr x24hr= 5,040,000x7 days= 35,280,000x4 weeks= 141,120,000 for 28 days so please fix this very OP before you get a lot of massive macroers on campaign maps

**Comment by woodenstix** [comment]
the irony

**Comment by bls1999** [comment]
@jmarroqu the solution here is to ban macroing in campaign levels.  Also, macros don't record keyboard press sensitivity so it might be difficult to make a macro.

@jacob-grahn is it possible to only make the levels give the exp bonus if they're entered on the campaign tab?

**Comment by Jmarroqu** [comment]
That's funny cause how did I macro my alts all their prizes? without doing anything @bls1999 & Jiggmin has to do is when Happy Hour occurs in a server the Campaign bonus will disappear for an hour til the Happy Hour is gone that way it won't be too OP and still be useful for all campaign racers.

**Comment by bls1999** [comment]
@Jmarroqu I'm not familiar with making macros so I wouldn't know how easy or difficult it is to make one for campaign maps.  It's very possible that it's extremely easy and I just don't know.  That's why I think it would be a better route to ban macroing in campaign levels.

**Comment by woodenstix** [comment]
>macroing allowed!

>ban macroing!

**Comment by Jmarroqu** [comment]
No need to ban macroing on campaign maps when you can just stripe one of the x2 on the public servers. All it'll take when a Happy Hour appears Campaign bonus will be gone for that hour then once the HH is over the Campaign bonus will come back so that way regardless of a macro or no macro the exp is fair and will be the same since x2 will be from Campaign or Happy Hour. Dunno how you guys think it's hard when that's a easy solution to this one lol.

**Comment by bls1999** [comment]
@Jmarroqu I see two problems with what you said:

1) Why would you be against banning marching in campaign levels?
2) If you took away the campaign bonus during happy hours, simmers and macroers would have an advantage over normal players during that time.

The issue is more complex than just one simple solution.

**Comment by bls1999** [comment]
@Jmarroqu I understand that simmers/macroers won't be able to abuse the x4 anymore; However, the reward for being regular players would go away during HH in this scenario.

**Comment by Jmarroqu** [comment]
For example, my friend is getting up to 4,200 for 2 mins. If you get rid of that x2 (for Campaign) it'll go back down to 2,100 which may be a lot to you but in a normal sim when a Happy Hour shows up at most you get is 2,000-2,200 a sim when macroing/simming (depending on your accounts you're using). What do you mean by "rewards" when 4p campaign will always have a prize so irdk what you mean by that?

**Comment by bls1999** [comment]
The point of adding a reward for being regular players is so simmers and macroers don't have an unfair EXP gain advantage.  As the idea proposes removing the bonus during happy hours, this will in turn restore the advantage to simmers/macroers.

**Comment by Jmarroqu** [comment]
Yeah, the exp bonus was design to give racers more exp or at least close enough to simmers/macroers that way they won't complain when all they do all day is play Campaign or ATB maps. But I mean if you're getting rid of Campaign Bonus I just mean the x2 not the prizes so dunno why would the simmers/macroers get more "advantages" when it'll be the same how it used to at least how I am seeing it. By removing x2 everyone will still be able to get the same prizes by racing but the exp you get will be the only thing that'll change when there's a Happy Hour but anyways if there was a better idea of how to contain this fix then let me know cause atm it seems i'm the only one who's actually trying to find solutions for this thread.

**Comment by bls1999** [comment]
I think it would be fine to keep the x4 bonus during HH, adding the rule that marcoing in Campaign maps won't be allowed. That will give racers an extra incentive not to sim/macro no matter if it's a HH or not.

**Comment by Jmarroqu** [comment]
So how would you spot players from buying a Private Server and macroing in there? I mean bad enough now you're gonna be like "Oh all Gods of Glory are macroing campaign" when I stack my usual Happy Hours on GOG?

**Comment by bls1999** [comment]
Remove the bonus on private servers to prevent private campaign marcroing.

**Comment by Jmarroqu** [comment]
So why can't you do the same for public servers while Happy Hour is on x) but okay I like that idea for the ps.

**Comment by bls1999** [comment]
Okay, so this is what the idea is now (as I understand it):

During HH:
 - On public servers, x4 bonus for campaign levels (on the campaign tab)
 - On private servers, standard x2 HH bonus server-wide

Without HH:
 - On public servers, x2 bonus for campaign levels (on the campaign tab)
 - On private servers, no extra bonus for campaign levels

**Comment by Jmarroqu** [comment]
Other than people saying "denying their right to get extra bonus on Private Servers" but that's up to Jiggmin tbh

**Comment by bls1999** [comment]
Alright, @jacob-grahn

**Comment by jacob-grahn** [comment]
I'd rather not do anything that complicated an confusing. I'll probably replace the campaign 2x bonus with something else.

**Comment by bls1999** [comment]
@jacob-grahn

Unless there's something I'm not considering, I don't think it would be too confusing.  The script would just check for a private server by taking the guild ID of the server, and then if it's anything other that 0 then the bonus wouldn't be applied.

**Comment by jacob-grahn** [comment]
I think the confusing/hard part would be trying to explain to people why their private servers give less exp than the public servers.

**Comment by woodenstix** [comment]
4x exp?
how about +100% exp so that we get 3x with HH instead?
