### ISSUE TITLE
Issues buying EE and possibly other items

### ISSUE THREAD

**Issue by EternalUF** [jacob-grahn/platform-racing-2-server#154]
We've received reports users are receiving this error from Kong: https://prnt.sc/i89dhb

And this is from trying to buy Epic Everything, but Colind was able to buy Happy Hours from the vault without issue so I'm not sure what the issue could be.

**Comment by trans1000** [comment]
i purchased frost djinn yesterday, so its not an error with vault as a whole. The problem persist when using different wifi networks/computers. I would try making a different kong/pr2 account, but i dont want to purchase more kreds

**Comment by bls1999** [comment]
It looks like it's an error with EE.  I'll look into it later.

**Comment by jacob-grahn** [comment]
This should be fixed now!

**Comment by trans1000** [comment]
thank you!!

**Comment by EternalUF** [comment]
Thank you @jacob-grahn!!!
