### ISSUE TITLE
Email validation may filter out valid emails

### ISSUE THREAD

**Issue by aaaaaa123456789** [jacob-grahn/platform-racing-2-server#16]
https://github.com/jacob-grahn/platform-racing-2-server/blob/cdb42c20ffe42656b553514d0cd0a08184de2b3e/server/fns/data_fns.php#L58

This validation of an email address is simply wrong; there's no whitelist or blacklist for characters in email addresses. The only requirements that can be drawn from the various specs interacting here are:

* There must be a @ character somewhere in the address.
* The string to the left of the @ character cannot be empty.
* The string to the right of the @ character must contain at least one period, not begin with one, and have at least two characters after the last one.

I've personally seen many (valid) email addresses that would fail the validation implied by this regex. For instance, I've seen addresses with exclamation marks in the username (i.e., before the @) part of the address.

**Comment by aaaaaa123456789** [comment]
(Also, I can't help but point out that "obscene" is misspelled repeatedly in that same file. :stuck_out_tongue: )

**Comment by aaaaaa123456789** [comment]
Off the top of my head, a regex that would contain those requirements would be `.+@[^@]+\.[^\.@]{2,}`. I haven't validated it, though.

**Comment by jacob-grahn** [comment]
I once wrote a program involving balloons. I misspelled the word balloon an incredible number of times, but it all worked because it was always misspelled the same way!

It doesn't look like that valid_email function is actually used anywhere in the multiplayer server, so I just deleted it. Thanks!
