### ISSUE TITLE
Staying Alive Sale

### ISSUE THREAD

**Issue by LP-PR2** [jacob-grahn/platform-racing-2-server#160]
So.. we're dead now?

Seriously, would be nice to have this sale back. The pricing for the items seem really expensive now that this sale has been going for a long time.

**Comment by bls1999** [comment]
@jacob-grahn if you still want the monies but want to put the sale back, maybe make the sale 50% instead of 75?

Basically, the reason people could afford to buy items from the vault was because you get 10 free kreds for signing up to Kong.

**Comment by LP-PR2** [comment]
@bls1999 the only way people would be able to buy things is by using that method, if the main goal is to aim this game at kids, adding a store for these prices is really unreasonable. Having to pay $10 in order to be able to use 2 colours on your character is insane. You need to look at it at a reasonable standpoint and a way that will actually benefit Jacob.

**Comment by FearsPR2** [comment]
I was just thinking about how problematic the cheap private servers for a day could be with the sale. If you do decide to put the sale back (plz papa jiggy) then I'd be perfectly fine with you either removing 1 day guild servers entirely, or make them cost a lot more than 12 on sale.

**Comment by bls1999** [comment]
I think the idea @FearsPR2 had is probably best.  It's problematic to have an excess amount of private servers.  That way, normal users can still purchase things.

@LP-PR2 that's kind of the point of a store; you buy things.  The Vault has always been an optional part of PR2.  Buying private servers gives you no advantage except a private place to sim/macro.

**Comment by jacob-grahn** [comment]
There will be more sales. I just don't want them to be hard-coded in the source code like they have been. I plan to set up some "sale" data in the db that changes from time to time, and read the data from there.
