### ISSUE TITLE
No random happy hours?

### ISSUE THREAD

**Issue by Stxtics** [jacob-grahn/platform-racing-2-server#166]
I don't know if this is just bad luck but there has not been a random happy hour spawn in almost two days. 
https://i.imgur.com/cIdjweH.png 

Has the system been changed so that they do not occur as often or have they been removed completely? 
Or is it just an error?

**Comment by FearsPR2** [comment]
I’m hoping this is a bug after adding the happy hour stacking. 

Hopefully random happy hours will make a swift return to the game, they’ve been missed. :’(

**Comment by jacob-grahn** [comment]
Yeah, I broke this when I added happy hour stacking. If someone wants to tackle it, I think the best way would be to add a timer with a random delay to multiplayer_server/HappyHour.php. When the timer is up, just call self::activate.

**Comment by EternalUF** [comment]
Random HH's are back :p
