### ISSUE TITLE
Your set updates only when you logout

### ISSUE THREAD

**Issue by Antonhs30000** [jacob-grahn/platform-racing-2-server#17]
If I change my outfit and click my name, it won't change unless I log out, this needs to be fixed.
Player.php

**Comment by jacob-grahn** [comment]
At the time, I didn't want the database to get flooded with zillions of updates per second. Now that there aren't as many players it shouldn't be a problem to save every time someone changes their outfit.

**Comment by aaaaaa123456789** [comment]
You might want to use a cache if that's an issue. Something like redis or memcached would help.

**Comment by bls1999** [comment]
I have a pull on the way that will fix this.

**Comment by bls1999** [comment]
Fixed in pull #24, commit 2d1df16.
