### ISSUE TITLE
Happy Hour Options In Vaults Of Magic

### ISSUE THREAD

**Issue by Jmarroqu** [jacob-grahn/platform-racing-2-server#175]
Since Happy Hours are able to stack now I was wondering if now we can introduce Happy Day where you can buy pre-stack Happy Hours instead of clicking in and out. I liked the idea of Fears maybe when we click on "buy Happy Hour" it will give you options instead of just the 1 hour. Maybe like this, Happy Hour 1Hr=50 kreds, 2hr=100 kreds, 4hr=200 kreds, 6hr=300 kreds, 8hr=400 kreds, 10hr=500 kreds, 12hr=600 kreds, 14hr=700 kreds, 16hr=800 kreds, 18hr=900 kreds, 20hr=1,000 kreds, 22hr=1,100 kreds, 24hr=1,200 kreds. The kreds value didn't change they're still 50 kreds per happy hour. I don't want no alternative ways "why don't you use a macro to buy the happy hours" cause I don't want to waste an hour of doing that or "This is a bad idea because too much exp" No cause the exp is still the same amount you get per happy hour just wanting an option to do more than 1 Happy hour. If you feel like you don't want to support this then instead of causing drama just put a "thumbs down" but whoever is in support put a "thumbs up" thanks for your time and hopefully I can get an answer from @jacob-grahn instead of getting a close thread.

**Comment by bls1999** [comment]
I don't believe options like that can be added without a client modification.

**Comment by LP-PR2** [comment]
But adding the artifact as it's own entity can?

**Comment by Jmarroqu** [comment]
I was talking to @fourst4r and he said that Jiggmin can't make an option within the item without modifying it. So instead of asking for "Options for pre-stack Happy Hour what about more items about Happy Hour. Like "Happy Hour x3" "Happy Hour x6" "Happy Hour x12" "Happy Hour x18" "Happy Hour x24" With the proper amount of kreds. 50 kreds per Happy Hour

**Comment by bls1999** [comment]
Seems like it would clog the vault and just be unnecessary.

**Comment by Jmarroqu** [comment]
@bls1999 If you've nothing nice to say other than putting my request idea down can you stop posting your negative explanation and just put a thumbs down and leave? Anyways, not like you're in charge of the VoM space. The items I see that can get rid off is "Super Booster" its free and not even use as much to be honest. All of the "Guild de" items are probably the same not bought a lot. Happy Hour, Private Server, Rank tokens, Epic Everything, and the 3 different set you can get are probably the only thing that are even giving him money. Anyways, again all I want is @jacob-grahn to reply and if he's against it I'll stop asking and we can move on.

**Comment by bls1999** [comment]
Sorry for expressing my opinion on you idea…?

**Comment by woodenstix** [comment]
@bls1999 your opinion does not matter if it's Colind (im dead rofl)

@Jmarroqu what's the point of making another ISSUE to continue about happy hours when you can just simply go to closed issues and type there, because you STILL CAN RESPOND TO CLOSED ISSUES HAVE YOU NOT YET REALISED THIS

Edit: supporting this idea but since colind is a little bitch i disagree

**Comment by LP-PR2** [comment]
Can we buy name changes in vom?

**Comment by bls1999** [comment]
This would likely also require a client edit.
