### ISSUE TITLE
Folding awards still don't work

### ISSUE THREAD

**Issue by bls1999** [jacob-grahn/platform-racing-2-server#179]
This is becoming worse than the dreaded tabs.

**Comment by woodenstix** [comment]
no u

**Comment by jacob-grahn** [comment]
I think I just had a bad path in the require_once. It worked when I tested it in that directory, but not when the script was called by cron.

Hopefully it works now :crossed_fingers:

**Comment by bls1999** [comment]
Yup, that did it. Thanks @jacob-grahn!
