### ISSUE TITLE
How Many Days/Months Are Left On A Private Server 

### ISSUE THREAD

**Issue by Jmarroqu** [jacob-grahn/platform-racing-2-server#181]
Guild Leader should be able to have a way to check how many days/months are left on their private server. Maybe if you type on the Pr2 main chat "/ps" it will say something like this; The [private server name] has [days/months] left and will expire in [whatever days/months it has]

**Comment by EternalUF** [comment]
This is a pretty cool idea, but I feel this isn’t the place to post suggestions :/ I would refer to Grahn.io/feedback

This issues list is suppose to be with issues within the pr2 repo.

**Comment by woodenstix** [comment]
YoU aRe JuSt A hAtEr GiVe VaLiD oPiNiOnS aNd DoNt CoMmEnT iF yOu Do NoT lIkE mY iDeA pLz!

**Comment by bls1999** [comment]
@Stxtics is currently working on a function that will allow this to be done.  It may be /timeleft to be more self-explanatory.

**Comment by woodenstix** [comment]
OR BETTER YET, COUNT FOR HOW LONG YOU PURCHASED YOUR SERVERS FOR! WOW! WHAT A FIND!

**Comment by Jmarroqu** [comment]
@jacob-grahn http://prntscr.com/ielnfn Since Adak deleted Gods of Glory twice or three time and since you had to put the private server I am assuming that's why it's giving us the error "This is not a private server." so we were just wondering if there was a way to fix it or tell us how many days/months you put for us and how much is remaining, thanks.

**Comment by bls1999** [comment]
The code was faulty, that's my bad.  It'll [hopefully] be fixed with #190.
