### ISSUE TITLE
Random Level Search

### ISSUE THREAD

**Issue by ProPlayzBlitzCrank** [jacob-grahn/platform-racing-2-server#185]
http://pr2hub.com/levels_by_random.php
Can this be fixed? It would be really helpful when I do my contest instead of trying to find a decent place to hide.

-Shane1334

**Comment by Stxtics** [comment]
This was removed due to it not really having any use in game. See more here - https://github.com/jacob-grahn/platform-racing-2-server/commit/61babcbc152087cbb3b5cda24fffe622bfab50f8

**Comment by ProPlayzBlitzCrank** [comment]
:(

**Comment by bls1999** [comment]
If this were to be added back, I'd think rate limiting should be added as well.

**Comment by bls1999** [comment]
Added to #184.
