### ISSUE TITLE
FAH Rewards

### ISSUE THREAD

**Issue by PR2SteamPower** [jacob-grahn/platform-racing-2-server#186]
whats the go with F@H rewards, i have been waiting almost 10 days for my 5th token.
and i know i'm not the only one waiting.
heaven has been waiting around 16 days for his 4th token?!? whats happening? i thought the rewards were fixed?!?!?!??!?!?

**Comment by bls1999** [comment]
Yeah, it's an ongoing issue, unfortunately.  I have no idea what needs to be done to fix it. @jacob-grahn

**Comment by bls1999** [comment]
Fixed!
