### ISSUE TITLE
Admins can't set the custom campaign

### ISSUE THREAD

**Issue by bls1999** [jacob-grahn/platform-racing-2-server#195]
The database functions need edits from you in order to be functional @jacob-grahn.  Maybe see if the database function for Campaign of the Fortnight's campaign setter still exists and add the ability to set prizes/prize types?

See 15d96bf for more details.

**Comment by jacob-grahn** [comment]
Good to know that php has a `range` function that can be used for loops!

@bls1999 Test this out some and see what happens. I would test it, but I'm not an admin. :stuck_out_tongue_closed_eyes:

**Comment by bls1999** [comment]
LOL

**Comment by bls1999** [comment]
@jacob-grahn it works! The only thing that could be improved is the server needs to restart in order for the prizes to take effect.
