### ISSUE TITLE
Racer Exp Solution 

### ISSUE THREAD

**Issue by Jmarroqu** [jacob-grahn/platform-racing-2-server#202]
A few people and I decided to see if there was a way we can make Racers get more exp than simmer but doesn't get abused so me and 898ppp decided what if Campaign and ATB aka All Time Best have exp multiplier? Campaign would get about x1.75 more exp and ATB aka All Time Best would get x1.5 more exp. We decided to pick a map where we would get the most exp and we agreed that Exp Grind lll would be it. 898ppp said at most you can generally get is 400 exp and at most 800 exp after all the WBB are gone. So if you do 400 x1.75 you would get  700 exp / 2 mins (or under) and if you still have the WBB exp and get 800 x1.75 = 1,400 exp / 2 mins (or under) since generally all racers rarely finishes their WBB or even play that long I would say this would be a fair solution for all racers/players that just play all Campaign maps and ATB maps. If happy hour started on a public servers and you're racing all the exp would be double so 1,400~2,800 exp (under 2 mins) is really better than simming when at most we can get is 2,000 through 2,400 in 2.5 mins (Just depends on the ranks on the 3 alts/accs you use to sim/macro. @jacob-grahn I think this is fair enough solution for all racers.

**Comment by bls1999** [comment]
Hi @Jmarroqu, please post suggestions on the PR2 Suggestions forum on JV2.

More info: https://github.com/jacob-grahn/platform-racing-2-server/blob/master/README.md

**Comment by Jmarroqu** [comment]
Closing this due to Jiggmin replyin in Fearspr2 so yeah ~
