### ISSUE TITLE
Admins can't pro/demote mods

### ISSUE THREAD

**Issue by bls1999** [jacob-grahn/platform-racing-2-server#21]
@jacob-grahn 

After the edits to pr2_moderation.php, mods can't promote or demote mods.  The issue is the command path.  I fixed this in pull #22.

**Comment by bls1999** [comment]
Oh, I figured it out.  When you edited the shell command, you forgot to include /commands/ before promote_to_moderator.php.

**Comment by jacob-grahn** [comment]
Pull #22 has a bunch of changes, so I'll set aside some time to look at it later. For now, I just updated the command paths. The update should be running on Isabel right now if you want to test it out.
