### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by bls1999** [jacob-grahn/platform-racing-2-server#211]
PR2 is intermittently being plagued by a 502 Bad Gateway error upon trying to access files on the http server.

**Comment by Myst1cZ** [comment]
@bls1999 I guess you might already know the cause of it.

**Comment by bls1999** [comment]
@Myst1cZ what are you angry about this time :laughing:

**Comment by Myst1cZ** [comment]
@bls1999 Not really mad about anything but it's just an way to get even with you giving me such long ban.

**Comment by EternalUF** [comment]
Blahhhhhh.... @jacob-grahn Pls.

**Comment by bls1999** [comment]
:thinking: :thinking: :thinking: :thinking: :thinking: :thinking: :thinking: :thinking: :thinking: :thinking:

**Comment by jacob-grahn** [comment]
Is it any file, or something specific?

**Comment by EternalUF** [comment]
All files seem to be affected :(

**Comment by Jmarroqu** [comment]
502 isn't the only error that Pr2 gets it goes the same with 504 bad gateway error just saying

**Comment by bls1999** [comment]
Yeah, at the time I posted it was just 502, but it looks like it evolved ¯\_(ツ)_/¯

**Comment by jacob-grahn** [comment]
Is this still happening?

**Comment by jacob-grahn** [comment]
I'm trying to figure out if it's only a DDoS problem, or if something else is messing up from time to time. If you guys could post the next time it happens, I'll check to see if it lines up with an attack.

**Comment by woodenstix** [comment]
No, no, I am ddosing. I have proof.
