### ISSUE TITLE
[Question] PR2 Source Code

### ISSUE THREAD

**Issue by bls1999** [jacob-grahn/platform-racing-2-server#212]
@jacob-grahn 

Someone with whom you corresponded in 2017 told me that you said you found a copy of PR2's ActionScript source code.  A couple of questions:

- Is it true?  If so...
- Do you intend to do anything with that?
- Would you be open to the possibility of letting the public make contributions and/or edits?

**Comment by jacob-grahn** [comment]
Nope, sadly not true

**Comment by bls1999** [comment]
:(
