### ISSUE TITLE
Update_guild.php

### ISSUE THREAD

**Issue by EternalUF** [jacob-grahn/platform-racing-2-server#213]
Returning an Error: Could not perform query. when trying to update guilds.

**Comment by bls1999** [comment]
I can fix this, I think.

**Comment by bls1999** [comment]
Fixed in #214

**Comment by EternalUF** [comment]
Returns: Error: Could not initiate the owner change. After fix #214

:((((((((

**Comment by bls1999** [comment]
@jacob-grahn

**Comment by jacob-grahn** [comment]
I just tested this, and it seemed to work?

**Comment by EternalUF** [comment]
You are correct! Awesome!
