### ISSUE TITLE
Pr2 Servers Getting DDOS by Gerry (Pr2 Servers was getting super unstable because of this)

### ISSUE THREAD

**Issue by Jmarroqu** [jacob-grahn/platform-racing-2-server#220]
I know that some ddos protection cost $ and it's very expensive but @jacob-grahn I think you should really consider of getting a good one because Platform Racing 2 cannot afford to go down in player because of a angry kid who got banned because of their own stupidity. I think setting up a DDOS protection out of VoM $ you're making since I think you're getting a lot of buys from me since buying Happy Hours like crazy should be able to pay for any good DDOS protection.

**Comment by bls1999** [comment]
I would also gladly contribute money to go to buying DDoS protection.

I think the reason why both the multiplayer servers and the http server were affected is Gerry was abusing a script that accessed the database a lot (@Antonhs30000's scripts).  I'm in the process of adding rate limiting for those and other scripts that access the database and should have a pull put together within the next few days.

**Comment by woodenstix** [comment]
he didn't ddos, i did!

**Comment by jacob-grahn** [comment]
If you're spending a lot of cash, it'll be a month or two before I get it from kong. :hourglass_flowing_sand: 

I am paying ten bucks a month for supposed DDoS protection from vultr, but it seems to not be doing much. I think their protection is triggered by a large volume of traffic coming in, but the attackers are hitting weak points in PR2 that don't need much traffic to bring it down.

In the meantime, I set up a global rate limit on anything that uses the database here: https://github.com/jacob-grahn/platform-racing-2-server/blob/master/http_server/fns/db_fns.php

Right now it's set to a max of 15 requests per 30 seconds, which hopefully won't mess up any regular use.

**Comment by EternalUF** [comment]
I believe adding the rate limit on dB requests is highly benificial, and should stop server crashes,l thank you @jacob-grahn !!
