### ISSUE TITLE
Folding awards still not fully fixed.

### ISSUE THREAD

**Issue by Stxtics** [jacob-grahn/platform-racing-2-server#221]
Folding awards seem to be fixed mostly but I have still find a reason for them not to work. I folded my account Spiro9988 when folding awards were not working. At the time it had 1 token that I folded like 2 years ago. Eventually I got 1 token even though I folded enough for 3. Then when the PM fix got added I got the third token and the PM for getting the third token. 

Now the issue is that on the same day I folded Spiro9988 I folded an account called Statics, that account had 0 points before I folded it. It now has enough for 3 tokens but I have still not got them. There is another account I folded an that also did not get tokens. Maybe the folding script or whatever it is, is not checking for new users or something. I'm not really sure but it has been 11 days since I folded Statics 1,000.

**Comment by Jmarroqu** [comment]
Damn that sucks I hope Jiggmin can fix the fah ASAP

**Comment by Stxtics** [comment]
Spiro9988 ( the account that got the other two tokens) and Statics ( the account which still doesn't have any tokens ) are online at the same time because I am macroing them lol :p. Another account which also had no tokens and still has none is also online at the same time.

**Comment by Jmarroqu** [comment]
Maybe you should make a program that will allow only Pr2 Admins to give players their own fah prizes? Like they can only give out 5 rank tokens but has to check the fah page to see if they earn the points if there isn't a way to perm fix this and of course they give the Crown and Cowboy Hat.

**Comment by woodenstix** [comment]
..so that they could give admins and mods themselves 5 tokens. I honestly appreciate your efforts but you should know that staff members give them everything, so.. :P

**Comment by bls1999** [comment]
@woodenstix please read @jmarroqu's post again.  He's suggesting having the admin tool check the F@H page to validate the request.

Personally, I think it would just be easier on us and on Jiggmin to definitively fix the F@H rewards.  We don't want to be manually awarding them all the time.

**Comment by bls1999** [comment]
Also, @jacob-grahn, I had already had a F@H record and got my 4th token within a day of you submitting your most recent fix.  I think @Stxtics is spot-on with this theory.

**Comment by woodenstix** [comment]
>has to check the fah page to see if they earn the points if there isn't a way to perm fix

So the program automatically "gives" rewards. 

Nice.

**Comment by jacob-grahn** [comment]
There was indeed a problem with new f@h rows not being created for new folders. Really fixed this time?

**Comment by Stxtics** [comment]
Yep thanks, I got my tokens. The only minor issue I would say is that the PMs went, Joining team, 500 points, 1000 points, 1 point.
