### ISSUE TITLE
New idea for player bonuses

### ISSUE THREAD

**Issue by bls1999** [jacob-grahn/platform-racing-2-server#245]
I was speaking with @Jmarroqu and 898ppp/Dagg, and we came up with an idea to solve the disproportionate EXP issue between players and simmers/macroers.

What if we reduced the amount of EXP that EXP hats give on Campaign?  Instead of giving +1x per hat, Dagg crunched the numbers and figured out that +0.4x would give players nearly the same bonus as simming/macroing 24/7, making it a viable reward for people to play on Campaign instead of sim.

We also discussed raising the artifact bonus, which would, in turn, cause more people to attempt finding the artifact (and not sim/macro while doing so).

I made [a commit](https://github.com/jacob-grahn/platform-racing-2-server/pull/244/commits/c9e883dba7e3a3741454b409f901a2eb15e968b9) that includes these change to pull #244 (artifact was bumped to 15k).  Please let me know if you think this is a viable option.

**Comment by bls1999** [comment]
I'm going to close this since it was added in a recent pull!

**Comment by jacob-grahn** [comment]
This is an intriguing solution, let's see how it goes. People might get mad about their hats giving less exp, but they are getting double from being on the campaign so :man_shrugging:
