### ISSUE TITLE
Guest not able to earn Kongregate badges

### ISSUE THREAD

**Issue by EternalUF** [jacob-grahn/platform-racing-2-server#250]
@jacob-grahn It was brought to our attention by the Kong team that Guests aren't able to earn badges currently, could just possibly be fixed? If so, Kong has agreed to promote Pr2 on the front page possibly increasing Pr2's overall activity!

**Comment by bls1999** [comment]
@jacob-grahn if you could add the Kong API to the multiplayer servers, I could probably set this up by myself.

**Comment by Jmarroqu** [comment]
Take the deal @jacob-grahn we need more new players that way they can transfer to the PRF if and when it gets done!

**Comment by jacob-grahn** [comment]
The kong API lives in the client for the most part. I figure we can either try to hack the client to not check for guest accounts before submitting, or we can change guest accounts to look like regular accounts to the client.

**Comment by bls1999** [comment]
Could there be a column in the database called "guest"?  That way, when doing user_select, we could reference it by saying if($user->guest === true).

**Comment by Relokos** [comment]
More players, that'd be great!

**Comment by EternalUF** [comment]
Are we anywhere on this? @jacob-grahn @bls1999

**Comment by bls1999** [comment]
@EternalUF I haven't really had a chance to work on it yet. PDO conversion takes priority.

@jacob-grahn do you know if setting Guests' group client-side to something like 4 would allow them to receive badges?  I'm trying to think of the minimal amount of changes that would need to be made for this to work.

**Comment by bls1999** [comment]
This should be taken care of in #299.  I only applied the fix to one account in that pull for testing purposes.

**Comment by bls1999** [comment]
@jacob-grahn I think I'm going to take a look at the client code to try to crack this problem.  Any ideas on what I should search for?  I looked for `kongApi` and got a lot of stats submissions for the high scores page.

**Comment by bls1999** [comment]
In what I assume was formerly the script that handles logins, I found this code:
```as3
      public function class_165(param1:String)
      {
         var _loc2_:* = null;
         var _loc3_:String = null;
         var _loc4_:class_64 = null;
         var _loc5_:String = null;
         var _loc6_:URLVariables = null;
         var _loc7_:URLRequest = null;
         this.loader = new class_15(true,class_15.const_5);
         this.m = new LoggingInPopupGraphic();
         super();
         this.socket = Main.socket;
         class_12.commandHandler.name_1("loginSuccessful",this.loginSuccessful);
         class_12.commandHandler.name_1("loginFailure",this.loginFailure);
         §§push(true);
         if(Main.userName == "guest")
         {
            this.socket.write("guest_login`" + Main.domain + "`" + Main.version);
         }
         else
         {
            _loc2_ = new object();
            _loc2_.user_name = Main.userName;
            _loc2_.user_pass = Main.var_169;
            _loc2_.version2 = Main.version;
            _loc2_.server = Main.server;
            _loc2_.domain = Main.domain;
            _loc2_.remember = Main.remember;
            _loc2_.login_code = String(class_1.method_1(501,-523));
            _loc2_.login_id = param1;
            _loc3_ = class_10.method_35(_loc2_);
            _loc4_ = new class_64();
            _loc4_.method_97(String(class_1.method_1(507,-517)));
            _loc4_.method_123(String(class_1.method_1(505,-519)));
            _loc5_ = _loc4_.encrypt(_loc3_);
            _loc6_ = new URLVariables();
            _loc6_.i = _loc5_;
            _loc6_.version = Main.version;
            _loc7_ = new URLRequest(Main.const_3 + "/login.php");
            _loc7_.data = _loc6_;
            _loc7_.method = URLRequestMethod.POST;
            this.loader.addEventListener(class_15.const_4,this.method_228,false,0,true);
            this.loader.addEventListener(class_15.const_6,this.method_254,false,0,true);
            this.loader.load(_loc7_);
         }
         this.m.var_1.addEventListener(MouseEvent.CLICK,this.clickCancel);
         addChild(this.m);
      }
      
      public function loginSuccessful(param1:Array) : void
      {
         Main.group = int(param1[0]);
         if(Main.userName != "guest")
         {
            if(Main.userName != "")
            {
               Main.loggedInAs = Main.userName;
            }
            Main.userName = "";
            Main.var_169 = "";
            §§push(true);
         }
         else
         {
            Settings.init(Main.loggedInAs);
            this.var_560 = true;
         }
         this.method_456();
      }
```

If I may, I'd like to draw your attention to these two if statements:

```as3
         if(Main.userName == "guest")
         {
            this.socket.write("guest_login`" + Main.domain + "`" + Main.version);
         }
```

```as3
         if(Main.userName != "guest")
         {
            if(Main.userName != "")
            {
               Main.loggedInAs = Main.userName;
            }
            Main.userName = "";
            Main.var_169 = "";
            §§push(true);
         }
         else
         {
            Settings.init(Main.loggedInAs);
            this.var_560 = true;
         }
```

One thing to note is that `this.socket` = `Main.socket`.

A few theories I have:
 - `` guest_login` `` is being interpreted by the server as a switch to turn off badges (which is odd, because I can't figure out what part of the server receives `` guest_login` ``...).
 - If that isn't the case, `` guest_login` `` must be the client's "note to self" in a way.

However, I'm more certain about `Main.loggedInAs` having some bearing on if badge earning is enabled or not.  I can get any other code from the client if you need it @jacob-grahn. It may be encrypted beyond recognition, but I can get it. Let me know.

**Comment by EternalUF** [comment]
:(

**Comment by EternalUF** [comment]
:O
