### ISSUE TITLE
Derron in a crashing cycle 

### ISSUE THREAD

**Issue by EternalUF** [jacob-grahn/platform-racing-2-server#253]
???? :(

**Comment by bls1999** [comment]
This has to be due to an edit I made to pr2.php.  Don't restart any of the other servers because it'll happen to them too.

**Comment by bls1999** [comment]
Upon further inspection, it seems Derron is starting up fine... I am confusion.

**Comment by jacob-grahn** [comment]
Lol, confusion is about 50% of what programming is.

The error is:
Call to undefined function award\`Hat/Campaign/HH Bonuses\`exp X () in Game.php:596

**Comment by bls1999** [comment]
Fixed in the most recent pull! @jacob-grahn
