### ISSUE TITLE
[IMPORTANT] EXP Integer Overflow

### ISSUE THREAD

**Issue by bls1999** [jacob-grahn/platform-racing-2-server#257]
Thanks to extensive testing done primarily by 898ppp (Dagg), I believe that EXP gained in a single race that turns out to be more than 65,535 will exceed the amount able to be stored in the database by an unsigned `SMALLINT`, which will, in turn, cause an integer overflow on the user's total EXP needed for ranking.

If we're right, this is a huge bug that should be fixed ASAP.

**Comment by bls1999** [comment]
@jacob-grahn

**Comment by isokissa3** [comment]
I had some doubts about overflow and done simple test and looks like that MySQL don't throw exception but instead turns the numbers to lowerbound or upperbound.

If you try to insert or update `unsigned SMALLINT` with value of 333333333333 the result will be sadly 65535. All negative values are turned to zero. This looks like to work with any number

**Comment by jacob-grahn** [comment]
I don't think the db stores any individual race results, just a total exp and a total rank for each player.

**Comment by bls1999** [comment]
@jacob-grahn it seems that earning a fairly large amount of EXP (somewhere over 50k) breaks the EXP gain for that user, causes weird things to happen to their total EXP, and sometimes crashes the server.  I'm not sure if it's a server-side integer limit set, but it's definitely worth looking into.

**Comment by woodenstix** [comment]
nice didnt know pr2 was 16 bit

**Comment by aaaaaa123456789** [comment]
How would someone gain that much EXP to begin with?

**Comment by bls1999** [comment]
Looks like this is fixed. It was an issue with an overflow of awards on the EXP popup.
