### ISSUE TITLE
Delete_old_accounts.php

### ISSUE THREAD

**Issue by VipaPR2** [jacob-grahn/platform-racing-2-server#258]
As of now the script doesn't delete "userId: null" users that meets the requirement for deletion. "userId: null" users are accounts that have been created, but not logged into. Therefore all of them are rank 0 and does naturally have no levels. I'm not sure how to make the script delete "userId: null" users, but @bls1999 had a solution that could maybe work? Here it is: https://github.com/jacob-grahn/platform-racing-2-server/pull/243
Also, I'm wondering, how often does the script delete accounts?

**Comment by jacob-grahn** [comment]
It goes once a month, I think.

Another possible solution would be to just delete all accounts that don't have a pr2 section created.

**Comment by VipaPR2** [comment]
It doesn't look like it goes once a month. And yeah, that's a good idea.

**Comment by jacob-grahn** [comment]
You're right, it's not running monthly. I'm running the script now. It's pretty slow, so it might take a day or two to finish.

**Comment by VipaPR2** [comment]
Nice. Does the script delete the "userId: null" users though?
