### ISSUE TITLE
Banning/Warning

### ISSUE THREAD

**Issue by EternalUF** [jacob-grahn/platform-racing-2-server#259]
Bls tried fixing this in #255 I THINK, but when warning a user it returns: Error: Could not find a user named "J m i" on this server. and when banning from the client the ban isn't recorded, if you are somehow about to ban it only bans the IP's and throws errors for the username. Weird :shrug:

Edit: It looks like warning is working, but banning in the client gives Guest [] has been banned for 60 seconds. and does log or initiate the ban server side.

**Comment by woodenstix** [comment]
bob the builder 

can we fix it

bob the builder

yes we cant

**Comment by bls1999** [comment]
The banning error is a PDO thing caused by a faulty user_select_by_id call.  I fixed it in #261

**Comment by EternalUF** [comment]
Fixed!
