### ISSUE TITLE
Pull #24 may not use MYSQLI_ASYNC

### ISSUE THREAD

**Issue by bls1999** [jacob-grahn/platform-racing-2-server#26]
@aaaaaa123456789 @jacob-grahn 

I'm not entirely sure how to use MYSQLI_ASYNC with #24, specifically in get_artifact.php.  My pull definitely fixed the shell command usage, I just don't know if that utilizes the asynchronous database connection we want.

If it needs to be fixed so it uses MYSQLI_ASYNC, I think that could be done by editing DB.php (namely functions call and grab).  That being said, I have absolutely no idea how to make this happen and I don't want to break anything in the process.

**Comment by aaaaaa123456789** [comment]
That pull is absolutely massive. Anything you're asking about, specifically?

**Comment by bls1999** [comment]
@aaaaaa123456789 c03dc90 (commands/get_artifact.php) and b96f8f7 (commands/update_pr2_user.php).  Notice that 83fc657 (commands/demod.php) and 0d9af43 (commands/promote_to_moderator.php) offer spots to place the MYSQLI_ASYNC flag, whereas the other two don't.

Sorry for all of the commits grouped together.  I'm kind of a discord newb.

**Comment by jacob-grahn** [comment]
You're right, we'll have to modify server/fns/DB.php to be able to accept the flag.

**Comment by bls1999** [comment]
@jacob-grahn not sure that's in my wheelhouse.  Is that something you could do?

**Comment by jacob-grahn** [comment]
It is done!
