### ISSUE TITLE
Code style

### ISSUE THREAD

**Issue by jacob-grahn** [jacob-grahn/platform-racing-2-server#260]
I set up a code style checker to automatically validate pr2's code going forward. This will help keep the codebase from getting too wild, and it will catch syntax errors before they make it to the live server.

There are about a zillion "errors" left to fix before this code lines up with what the style guide wants, so this ticket will likely remain open for a while. All builds will show up as failing until this work is done.

https://travis-ci.org/jacob-grahn/platform-racing-2-server

The style it's using is called [PSR2](https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-2-coding-style-guide.md)

**Comment by BrokenBulb78** [comment]
That's cool!

**Comment by bls1999** [comment]
The only things that irk me about PSR2:
 - `{` for if/else, try/catch, functions, while, foreach, etc is on the new line
 - `}` for if/else and try/catch is on the same line as the next statement (`} else {`)
 - There are 4 spaces at the beginning of every line instead of a tab.

Other than that, it's great!

**Comment by woodenstix** [comment]
aaaa nice job but i doubt we should listen to bls because he is known to fuck up everything so yeah

**Comment by Myst1cZ** [comment]
@bls1999 I can agree on that, that style of coding looks weird to me.

**Comment by aaaaaa123456789** [comment]
You might want to make two separate builds in Travis, one that validates style and one that doesn't. That way, you can still test builds even when style fails. (2 builds failed = critical tests didn't pass; 1 build failed = critical tests OK, style didn't pass.)

**Comment by jacob-grahn** [comment]
I'm not quite sure how to set up Travis to run two different builds. As a slightly lazier solution, the build now runs two scripts. Once checks for style, and the other checks for syntax errors and unused variables. There are other checks that we can add, but for now I'm going to bask in the sweet green glow of pr2's first passing build.
