### ISSUE TITLE
Derron crashing

### ISSUE THREAD

**Issue by EternalUF** [jacob-grahn/platform-racing-2-server#266]
It seems like Derron is in a constant cycle of crashing again.... 🤔 Not sure why.

EDIT: #265 was suppose to fix this, but it seems like it didn't work correctly 🤷‍♂️

**Comment by jacob-grahn** [comment]
I'm going to run some tests on Derron. If you guys could crash it on purpose for the next half hour or so, it would save me some time. Thanks!

**Comment by bls1999** [comment]
@jacob-grahn you got it, boss. Also, logging out of Fred (and I suspect any account that uses my function `become_server_owner()`) crashes the server.  Not sure if this has to do with a variable scope/reference error or not, but it's worth looking into while tests are being run.

**Comment by bls1999** [comment]
Prizes are fixed!  The fred logout still breaks things tho

**Comment by bls1999** [comment]
I just crashed Isabel with the Fred logout, so hopefully that helps with debugging @jacob-grahn

**Comment by jacob-grahn** [comment]
The error I'm getting is that the 'head' is not set when trying to save a user's account. :man_shrugging:

**Comment by bls1999** [comment]
LMAO, I think I know how to fix that...

**Comment by bls1999** [comment]
@jacob-grahn just fixed it. There was nothing in Fred's head array, LMAO

**Comment by EternalUF** [comment]
Woooo!
