### ISSUE TITLE
Security Breach! Packet Sniffers can obtain your IP address and can then be traced 

### ISSUE THREAD

**Issue by Jmarroqu** [jacob-grahn/platform-racing-2-server#267]
It has come to my knowledge that recently certain players have been using packet sniffers to find peoples info on levels and if it only did that it wouldn't be big but if the staff and whats left of the player base cares about people finding their IP addresses as well as using a free IP tracer website or applications to find your physical location. I have verified that this works in PR2 and is accurate in a range of 20-50 miles and depending on your ISP can say what area of a town you live in its bad enough to be dealing with false accusations such as botting but this is a serious threat to all players and staff of the game if people want this game to still be around and not filled with actual hackers who can trace your location id suggest the staff work on patching packet sniffers so that the players IP addresses are not shown this can be remedied by having PR2 be used on a secure network with static IP addresses VPN's and so on I shouldn't have to be bringing this up if the staff who's job it is to keep the players safe and make sure the games rules whatever they are be enforced they should be taking this serious instead of allowing people to use these things just because they don't understand them. I have linked a video below which shows how certain packet sniffers are able to get peoples IP addresses just from online interactions without the other person even knowing its happening.

https://www.youtube.com/watch?v=hBcvX6GA5UQ

Every since Macros were allowed I have been experimenting with an application called TinyTask its a simple mouse recording application that basically has some advanced features. I was trying to prove that you can make play counts with a mouse recording application that can go super fast. If you record yourself with TinyTask you can search a level that has 4 finish block and 4  up arrow block under it and with that you can "macro the play counts" that resemble like you're botting I've done so with same levels that people who "reported the play counts on the campaigns" and other non comapign levels as well. If you go to "Options" on TinyTask and go to "Play Speed Fast" and "Continuous playback" and hit the "Start" button you'll see how fast you can go in and out the levels and since the Wireshark or other packet sniffers doesn't tell you if they hit the finish block or not you can't make that as "indisputable evidence" when it can easily be explained as well as recreated. I have been waiting to show them how its done to show them i'm innocent but because the system is guilty till proven innocent my request is being delayed to show i'm telling the truth. @jacob-grahn

**Comment by bls1999** [comment]
The reasons I didn't respond to your message:
1) I take 9 classes and have 2 midterms today
2) I'm in class until 6pm
3) I'm traveling home for spring break at the end of the day today

None of this is your fault, but please realize that I have a lot on my plate. This is why things like Ask a Mod exist and why I added @EternalUF to the conversation.  I am not ignoring this issue, and I am not ignoring you.

That being said, I think this is a huge issue that should be patched.  I'm not sure that I can do anything, so this would probably need to be @jacob-grahn.  An issue with your fix is that IP bans might not work.

**Comment by jacob-grahn** [comment]
PR2 doesn't send any data `client -> client`, it's a `client -> server -> client` kind of set up. A packet sniffer could tell you the ip of the server, but that's it.

**Comment by woodenstix** [comment]
trace my ip daddy bls

**Comment by LP-PR2** [comment]
ur ip is 69.420.133.37

**Comment by bls1999** [comment]
DOX'd af @LP-PR2 @woodenstix

**Comment by LP-PR2** [comment]
woah @bls1999 dont abuse ur privileges

**Comment by VipaPR2** [comment]
You are officially reported to the authorities for sharing personal information.

**Comment by BrokenBulb78** [comment]
Mine is 127.0.0.1, ddos pls @woodenstix

**Comment by woodenstix** [comment]
youre all wrong my ip is 80.08.13.5
