### ISSUE TITLE
Trying to log in while Guild de Artifact is enabled doesn't work

### ISSUE THREAD

**Issue by bls1999** [jacob-grahn/platform-racing-2-server#269]
You're infinitely stuck at the "Logging in..." screen.  I'm not entirely sure why this happens, but if I had to guess it would have something to do with the `verify_parts()` function in Player.php.

**Comment by jacob-grahn** [comment]
This looks like it's fixed on Isabel. A side effect that I didn't really think about until now is that I was testing with the PR2 Staff guild. You guys might need to log into Isabel and leave that guild before you can log into the other (unfixed) servers.

**Comment by bls1999** [comment]
@jacob-grahn cool stuff!  I didn't get a chance to test it, but I'll take your word for it.  If it's an issue, I'll reopen this.
