### ISSUE TITLE
Flavor text on prizes no longer appears

### ISSUE THREAD

**Issue by bls1999** [jacob-grahn/platform-racing-2-server#27]
The following pieces of flavor text are coded into the game (in parts/Prizes.php), but don't appear under the prize boxes where they have in the past:

 - EXP Hat: If you finish a race with this hat, it will increase your EXP gain by 100%!
 - Propeller Hat: Hold up while wearing this hat to float!
 - Santa Hat: Briefly freezes the blocks you stand on!
 - Party Hat: Wear this hat to become immune to lightning!
 - Top Hat: Stroll through vanish blocks with class!
 - Jump Start Hat: Waiting is slow! Start racing right away.
 - Moon Hat: Earn some super bright Lux!
 - Thief Hat: Steal other player's hats --even crowns!
 - Jigg Hat: Jump on the heads of your opponents!

An example of what I'm talking about: [click me for a youtube video](https://www.youtube.com/watch?v=Es0ofX-7oLs&t=8s) (see at 0:08)

I'm not sure if this is a flash issue or a server issue.  Either way, I think it is something to be investigated.

**Comment by bls1999** [comment]
The +5 EXP bonus popup doesn't appear either, but the bonus is awarded.

**Comment by Antonhs30000** [comment]
I think this is a client issue. @bls1999

**Comment by jacob-grahn** [comment]
Does the artifact prize description here show up?

https://github.com/jacob-grahn/platform-racing-2-server/blob/master/multiplayer_server/fns/artifact_first_check.php#L25

**Comment by bls1999** [comment]
It's passed to the client but it doesn't show, no.

**Comment by jacob-grahn** [comment]
I don't really plan to fix this, so I'm closing the issue.
