### ISSUE TITLE
Welcome PM not showing username and IP only ban issue

### ISSUE THREAD

**Issue by Stxtics** [jacob-grahn/platform-racing-2-server#278]
https://i.imgur.com/P3bbHYA.png 
Account username is not in the welcome PM.

Also clicking on this here for IP only bans https://i.imgur.com/vqnCZpt.png returns "Error: Invalid user ID specified."

**Comment by bls1999** [comment]
both are fixed in #295

**Comment by Stxtics** [comment]
I think I see what you changed @bls1999 but clicking on an IP of an IP only ban still says the same error. Also the welcome PM now looks like this. https://i.imgur.com/UnKFaDz.png (the account username is r3424234324)

**Comment by bls1999** [comment]
The changes haven't been merged to the server yet, so that's why the errors are persisting.

**Comment by Stxtics** [comment]
Oh, I thought it had because the error I got this time with the welcome PM was different.
