### ISSUE TITLE
Fixing Relokos

### ISSUE THREAD

**Issue by Relokos** [jacob-grahn/platform-racing-2-server#279]
Hello Jiggmin, I'm a user who goes by the name "Adak" and a few months ago I was banned for infiltrating a moderators account, now I was happy to accept this punishment however what then occurred was very surprising, all of the sets and hats that I had worked hard to earn were stripped from the account and the name of the account was also elongated as sort of a mockery attempt, I didn't think these actions were very justifiable by the moderators/administrators at the time and I was hoping you may be able to reverse these changes carried out against my account.

Thanks, Relokos.

**Comment by EternalUF** [comment]
I see your concerns, but this would make a great discussion in "Ask a Mod" on Jiggmin2.com, which Jiggmin himself checks frequently. This issues tab is specific for issues regarding any coding within the repo. Which is typically why Jiggmin doesn't respond to these types of things, I would assume and don't blame. So please, if you have any issues regarding any prior actions or decisions I'd point toward Ask a Mod. If they are legitimate.

**Comment by bls1999** [comment]
@EternalUF as he's in the "Very Banned" group (does not have access to Ask a Mod), I find it fit to respond here.

@Relokos you stole 3 moderator accounts, scammed to get literally hundreds of accounts, committed fraud, identity theft, cyber crimes, and really expect to be left with anything?  You don't deserve any recognition whatsoever.  Not only will you stay banned on PR2 forever, those bans will transfer to PRF as well.  I will not be returning any of your items I will not be unbanning you anywhere on any of your accounts, including JV2.  @jacob-grahn is obviously welcome to override me, as it's his game and his intellectual property, but if I were him, I wouldn't want a literal criminal on my site.

**Comment by Relokos** [comment]
Agreed something with Eternal.
