### ISSUE TITLE
Level unpublishing

### ISSUE THREAD

**Issue by EternalUF** [jacob-grahn/platform-racing-2-server#280]
Level unpublishing seems to be not working. It gives a "This level has been removed successfully. It may take up to 60 seconds for this change to take effect." Confirm though, but it never removes.

**Comment by bls1999** [comment]
I can look into this and submit a pull later.  I think it's probably due to some PDO changes by Jiggmin, though.

**Comment by EternalUF** [comment]
Not sure if #282 was supposed to fix this, or if #282 is running on Isabel or not, but it seems like this is still doing the same thing as before @jacob-grahn

**Comment by EternalUF** [comment]
This may actually be fixed.... Will keep ya updated!
