### ISSUE TITLE
Fast botting prevention

### ISSUE THREAD

**Issue by aaaaaa123456789** [jacob-grahn/platform-racing-2-server#285]
While there isn't much you can do client-side, and there are probably hundreds of vulnerabilities we don't know about, there's a simple way to prevent the fast botting that has been happening so far. It would require some DB changes, which is why I can't do it myself (and I honestly don't have the time to write the code right now), but it should be simple enough for someone else to write it without issues.

1. Add a column in the users table, recording the timestamp at which they were last awarded EXP. Initialize this value to something low (0 will work).
2. Whenever a user is about to be awarded EXP, retrieve this value from the database. If the value is not at least two seconds in the past (i.e., it's greater than `time() - 2`), disconnect the user. Otherwise, award EXP as usual and update this value.

Note that everything in step 2 must happen synchronously. You might want to create a separate thread for it, in which case you won't be able to disconnect the user as easily, but you can handle it as some sort of error and at least not award the EXP.

Since there is no way for a human player to earn experience less than two seconds apart, this will effectively stop this technique. (Considering the small bonuses involved, a sample +5 exp per 2 seconds would mean 7500 exp/hour. Any simmer can tell you that a simple macro can triple those gains without difficulty.)

**Comment by LP-PR2** [comment]
Good idea, but what if the disconnect is manually triggered and the user ends up getting wrongfully banned?

**Comment by aaaaaa123456789** [comment]
I didn't mention any bans intentionally — I wouldn't trust an automated watcher like this to correctly ban users. And there are no manual disconnections mentioned anywhere, either.

Is there some part of the post you didn't understand?

**Comment by bls1999** [comment]
If the value is not at least two seconds in the past (i.e., it's greater than time() - 2), disconnect the user. 
@aaaaaa123456789 I think this is what @LP-PR2 was referring to?

**Comment by aaaaaa123456789** [comment]
That would be automatic, not manual — and there is no way to earn experience in-game multiple times in two seconds. (I challenge you to try!)

**Comment by LP-PR2** [comment]
@aaaaaa123456789 i'll get back to you in 18 days

**Comment by aaaaaa123456789** [comment]
Why 18 days?

**Comment by LP-PR2** [comment]
@aaaaaa123456789 currently respecting my ban

**Comment by jacob-grahn** [comment]
The pr2 multiplayer server may be able to hold this info in memory, rather than sending it off to the db. The multiplayer server gets sent a user's info when they log in, and then any updates to that user are buffered and occasionally be saved to the db. When the user logs out, their info is saved one last time. It's an odd system that was designed to minimize the number of queries that needed to be performed from the multiplayer server.

**Comment by famelegend1** [comment]
I implemented this idea in my recent pull request :)

**Comment by bls1999** [comment]
^ @famelegend1's fix I think will solve this problem.

**Comment by bls1999** [comment]
@famelegend1 @aaaaaa123456789 revisiting this. What if we added a variable to the Player class like `$player->last_exp` which would hold the timestamp of the last time the user gained EXP on that login? So in `Game.php`, it would look something like this:
```php
if ($player->last_exp <= time()) {
    $player->socket->write("message`Botting is a no-no. :(");
    $player->remove(); // disconnect
}
```
I think on login it could be set to the login time as well.

This coupled with the 5 logins per minute limit would effectively stop botting, IMO. Thoughts?

**Comment by bls1999** [comment]
@aaaaaa123456789 you ninja'd me right as I was fixing it, lol

The idea is that if you're a human and gaining EXP properly, you won't be able to go into a level hit finish, and repeat all in however many seconds we determine to be appropriate.

**Comment by aaaaaa123456789** [comment]
Then a bot would just implement that delay.

**Comment by aaaaaa123456789** [comment]
Also, you still have the condition backwards.

**Comment by bls1999** [comment]
@aaaaaa123456789 true, but isn't the goal here to limit the usefulness of bots to the point where it doesn't make sense (or doesn't give an advantage) to use them over normal human gameplay anymore?

Also, I think I fixed the condition before you posted that second comment.

**Comment by famelegend1** [comment]
yeah i was confused at first because that condition would always be true, but i guess you fixed it

**Comment by famelegend1** [comment]
@aaaaaa123456789 the point is to fix the overpowered bots like ones that firebird used. it wont stop all bots per se, but the most powerful ones for sure

**Comment by aaaaaa123456789** [comment]
In that case, it would work.

**Comment by bls1999** [comment]
#524

**Comment by Stxtics** [comment]
Unless I'm missing something I don't really see the point in adding that. You don't get 5 EXP from already having a part so there is no need to worry about that. And if you finish a level in under 1 second you get 0 exp. If you finish a level in 2 seconds you get 2 EXP (with EXP hat) as shown here https://i.imgur.com/j97dbL2.png which is still only 30 EXP in a minute. I'm not saying it shouldn't be added because I guess this could be useful for multiple players being in the race and finishing fast as you get more exp for beating the players but it's not really preventing much unless you intended on bringing the +5 for already having a part back.
