### ISSUE TITLE
Vault of Magics broken

### ISSUE THREAD

**Issue by ShakeJunt01** [jacob-grahn/platform-racing-2-server#287]
I've been trying to buy Epic Everything in the Vault of Magic for the past 2 days but it keeps telling me that there's server errors. I tried with different accounts and it did the same sadly.

Would be appreciated if it could get fixed soon.

-$hake Junt

![server error](https://user-images.githubusercontent.com/37563497/37631300-653cc23a-2bbf-11e8-8d58-912e654b5f9f.png)

**Comment by Jmarroqu** [comment]
Remember, that isn't a Jiggmin issue, anything related to Pr2 items has to do with Kong not them, cause you know, even though they're staff and a creator they don't want to help their fellow Pr2 community.

**Comment by ShakeJunt01** [comment]
@Jmarroqu Bls1999 himsefl asked me to post my problem here so?

**Comment by bls1999** [comment]
@Jmarroqu it is in fact an issue with some code on the PR2 HTTP server.  I suspect it has to do with the guild de artifact fixes @jacob-grahn implemented.

**Comment by bls1999** [comment]
@jacob-grahn it seems the vault is broken further now. Clicking an item throws an error without going to the purchase screen first.

**Comment by jacob-grahn** [comment]
I made some changes which appear to have fixed the vault. If it's still broke, let me know about it here.

**Comment by bls1999** [comment]
@jacob-grahn in response to your message on Fred, the reason you're not an admin there is that server owners are currently set as temp mods when they log in.  #299 makes server owners admins on that server, minus all of the special real admin privileges.

**Comment by ShakeJunt01** [comment]
Thank you for the fix!
