### ISSUE TITLE
[Urgent] Special characters break guild titles, disable accounts

### ISSUE THREAD

**Issue by bls1999** [jacob-grahn/platform-racing-2-server#3]
If a user puts a special character in their guild title, it can break the guild.  This in turn will break all accounts associated with that guild, requiring admin intervention to fix.  Some have turned this into a fun game to see whose accounts they can break.  They'll mess up the guild and then leave it.  The worst part is: the staff don't have any way of knowing who it was.

Two possible fixes:

1) A regex check for the php that handles guild creating and guild information updating.  This can pretty much be copied/pasted from the user registration php and should take about 2 minutes with FTP access to PR2hub.

2) ^ and/or letting admins edit guild information/owners.

**Comment by Myst1cZ** [comment]
Original video i made on this: https://www.youtube.com/watch?v=5IJ8DzFCWBs

**Comment by aaaaaa123456789** [comment]
I'm going to take a shot in the dark and say this is a matter of encoding. This has traditionally been an issue with PR2 (remember when you could disconnect everyone in chat by sending malformed UTF-8 strings? A single `0x80` byte would usually do the trick), and thus it's very likely to pop up in many more places.

The solution comes in three parts here:

1. Ensure that the presentation layer (i.e., the Flash client) and the backend use the same encoding. UTF-8 is typically the sane choice for this, but as long as you cannot modify the Flash client you're stuck with whatever that uses.
2. Validate all input strings and trigger fatal errors on malformed ones. Anyone inputting an invalid string (as a username, password, chat message, level name, wherever) should be greeted with an error and a disconnection — there is no way to do this unintentionally, so there's no reason to have the server accept them.
3. Filter from the server all strings that cannot be handled by the presentation layer. This typically won't occur unless the Flash client is buggy, but we all know that it has its fair share of bugs. For instance, if the presentation layer will only handle strings as ISO-8859-1, you'll have to filter out all codepoints above 255.
