### ISSUE TITLE
Some issues to munch on 

### ISSUE THREAD

**Issue by EternalUF** [jacob-grahn/platform-racing-2-server#303]
Level publishing is throwing the error: Error: The level did not upload correctly. Maybe try again?

Creating a new account is making their user power client side appear as a guest, but it shows 1 in admin tools :/

There are currently 2 member-guest accounts online right now.
Some of which aren't newly registered accounts, so not sure :/

**Comment by EternalUF** [comment]
Apparently people who get the Guest power glitch are losing EE, this is no bueno

**Comment by EternalUF** [comment]
The issue is logging in with credientials, logging in by typing in credientials converts the account to a Guest account (Stripping all Epic upgrades from the account) using remember me, logging in the first time using the credientials, and then refreshing to get a remember me login (without typing credientials) converts the account back to a member.

**Comment by jacob-grahn** [comment]
If this is fixed, I can roll back the db to yesterday. The other option would be for the mods to fix people's accounts. I dunno how many accounts were affected, so that may not be doable.

**Comment by bls1999** [comment]
@jacob-grahn

If you could query recent_logins to determine the users that could've been effected, it might be easier just to roll back those accounts.  That way, guilds and other things of that nature won't be affected.

**Comment by bls1999** [comment]
I believe so, but just to be safe I'd restore pr2 as well, since logging out of guest accounts theoretically clears all parts and customization data.

**Comment by bls1999** [comment]
Looks like everything is all good!  Thanks! @jacob-grahn

**Comment by EternalUF** [comment]
Except for the level unpublishing stuff :(

**Comment by bls1999** [comment]
Yeah the parts are okay now tho.

With `upload_level.php`, the error being thrown is related to hash verification (as seen on [line 62](https://github.com/jacob-grahn/platform-racing-2-server/blob/fb7f77d08ad4b0b8f55991ecdeb0ca00c4f215ea/http_server/www/upload_level.php#L62)).  Did you change anything with this @jacob-grahn?

**Comment by jacob-grahn** [comment]
I think `id_to_name` is returning an object, while `upload_level.php` is expecting a string

**Comment by bls1999** [comment]
Fixed it @jacob-grahn, #306

**Comment by jacob-grahn** [comment]
So fast! :dash:

**Comment by jacob-grahn** [comment]
Taking out the S3 import from `upload_level` was a cool idea, but it looks like `s3_connect` doesn't import it either. We should probably add that in! The S3 class is kind of huge, so it might be good to take `s3_connect` out of `all_fns` (that should really be renamed...) Then the files that use s3 would just need to include `s3_connect`. Hope that made sense. I gotta go!

**Comment by bls1999** [comment]
@jacob-grahn S3.php is gone from the repo, so I assumed it wasn't needed?

**Comment by jacob-grahn** [comment]
Hahaha, that is a reasonable thing to assume! :laughing: 

I pushed some changes, and level uploads look like they're working!

**Comment by EternalUF** [comment]
Wooo!
