### ISSUE TITLE
Some people are still missing their EE/epic upgrades

### ISSUE THREAD

**Issue by bls1999** [jacob-grahn/platform-racing-2-server#307]
I'm guessing they were online when the rollback occurred?  The admins aren't doing anything because we don't know who had it and who didn't before the glitch.

@jacob-grahn is it possible that you could give us admins access to the epic_upgrades table of the db backup you rolled back so we can check if people actually did have EE?

**Comment by ShakeJunt01** [comment]
I logged in with Fears before it was ''fixed'', without reading the announcement and welp the EE on it just dissapeared. Then when it was said that the problem was fixed it didn't come back meh

**Comment by jacob-grahn** [comment]
I can send you a copy of the table

**Comment by bls1999** [comment]
@jacob-grahn Thanks!
