### ISSUE TITLE
Levels have passwords on.

### ISSUE THREAD

**Issue by Stxtics** [jacob-grahn/platform-racing-2-server#309]
Not sure what has caused this and why only some users have been affected but some users levels have passwords on. 
Examples of this are: 
- geminij
- Podqwerter

Those are the only two I have seen so far.

**Comment by bls1999** [comment]
I believe Justinbob100 had this problem too.  Does it happen every time or just certain times for certain users?

**Comment by Stxtics** [comment]
Yeah those users levels don't actually have passwords now, this might've been to do with the guest thing. Like when a users account became a guest it put passwords on their levels.

**Comment by bls1999** [comment]
I doubt that.  The users were still members in the database, but the server wasn't given that data.  It shouldn't have had any effect on levels.

**Comment by bls1999** [comment]
Is it possible they tried to save levels while Jiggmin was fixing the publishing system?  That could've messed it up.

**Comment by VipaPR2** [comment]
Apparently this happens when you create a new level. Just take a level from newest.

**Comment by bls1999** [comment]
Can anyone take a video?  I can't recreate this error on any member accounts.

**Comment by bls1999** [comment]
@jacob-grahn https://youtu.be/BZmbwERZ3wk

**Comment by bls1999** [comment]
I think I found the issue!  It should be fixed in #308.
