### ISSUE TITLE
FAH broken again :(

### ISSUE THREAD

**Issue by EternalUF** [jacob-grahn/platform-racing-2-server#310]
We are receiving reports FAH script isn't awarding parts/tokens again, I blame PDOcalypse.

**Comment by EternalUF** [comment]
Sweet, #308 should fix this

**Comment by bls1999** [comment]
should be fixed in #308. ya typed `fah_pdo_connect` instead of `pdo_fah_connect` @jacob-grahn

**Comment by bls1999** [comment]
@jacob-grahn There's a FAH query that has some weird multiple-statement queries.  I think this might be creating some problems with FAH prizes.  More info in #316.

**Comment by jacob-grahn** [comment]
Are the awards working now?

**Comment by EternalUF** [comment]
I believe so, I’ve been hearing people are getting parts/tokens. I’ll keep you updated if something changes, thank you so much, @jacob-grahn!
