### ISSUE TITLE
Searching by course title is weird

### ISSUE THREAD

**Issue by Stxtics** [jacob-grahn/platform-racing-2-server#317]
As first mentioned by Dagg on the discord server, searching for levels searches for two words separately.  
"when you search for multiple words now in course title (e.g. "Frust Challenge") it will search for the two terms separately, so it'll show results for both frust and challenge, but to find "frust challenge" specifically you rely on luck". I don't really remember but apparently it was not always like this. Is it possible searching for levels by course title could be changed to search better or is there a reason behind this?

**Comment by bls1999** [comment]
I have no idea why this is the case, but I really like it.  If you want to search for 2 words (i.e. frust challenge), use quotes around the phrase (i.e. "frust challenge").

If this is something @jacob-grahn is interested in fixing, then fixed it shall be; However, I think it makes the tool more powerful and intuitive.

**Comment by Stxtics** [comment]
Oh I see I guess it is not too bad then.
