### ISSUE TITLE
Level Backups and Campaign Setting

### ISSUE THREAD

**Issue by bls1999** [jacob-grahn/platform-racing-2-server#320]
- Level backups are broken. A 500 internal server error is thrown when trying to execute something after [Line 36 on backups.php](https://github.com/jacob-grahn/platform-racing-2-server/blob/744eb300e306e22306ad5eecba1dca84de42eb61/http_server/www/backups/backups.php#L36). I can't figure out what it is for the life of me; I'm guessing it must have something to do with the S3.
 - Campaign setting throws an error (which I emailed to you in case you didn't want it shown here).
 - Another thing that I emailed you about pertaining to security.

**Comment by jacob-grahn** [comment]
* Added a missing import to backups.php, dunno if that fixed it but we can hope.
* Haven't looked into the campaign error yet, will do
* Got it

**Comment by bls1999** [comment]
I'm not sure if this is still a thing... gonna close. I'll reopen if it's still an issue.
