### ISSUE TITLE
@jacob-grahn accidentally demoted you

### ISSUE THREAD

**Issue by bls1999** [jacob-grahn/platform-racing-2-server#331]
Sorry :s

**Comment by woodenstix** [comment]
@bls1999 I accidentally just demoted you, please check PR2 if you want your admin back.

**Comment by bls1999** [comment]
@woodenstix :fearful:

**Comment by BrokenBulb78** [comment]
These things happen ¯\_(ツ)_/¯

**Comment by jacob-grahn** [comment]
It's cool, I needed a vacation anyway
