### ISSUE TITLE
Artifacts giving out multiple sets of EXP

### ISSUE THREAD

**Issue by bls1999** [jacob-grahn/platform-racing-2-server#334]
So apparently, if you get the artifact, change your IP, and then get it again, you get the EXP twice.  I saw there were some edits made to the artifact checks (i.e. the check on login, etc), so could that have something to do with it?

We temporarily paused our artifact cycle within the staff, set it on a new level, and unpublished said level. @jacob-grahn

**Comment by jacob-grahn** [comment]
Guess this means I _shouldn't_ take things out if I don't remember what they do?

**Comment by EternalUF** [comment]
Can you check your email regarding this? @jacob-grahn

**Comment by Stxtics** [comment]
Put artifact on a level with super hard long unbruteforceable password.

**Comment by bls1999** [comment]
Still ways to get past it, unfortunately. :/

**Comment by Stxtics** [comment]
Make rank 99 required and use Fred to get it?

**Comment by bls1999** [comment]
Passwords and minimum rank requirements can unfortunately be defeated easily. :(

**Comment by jacob-grahn** [comment]
If you make a pull that locks it to server id 889 (fred), I'll get it rolling.

**Comment by bls1999** [comment]
Fixed!
