### ISSUE TITLE
Accounts with base rank < 3 can chat but not send PMs

### ISSUE THREAD

**Issue by Stxtics** [jacob-grahn/platform-racing-2-server#336]
This isn't really an "issue" but accounts that have enough tokens so that their rank is => 3 can chat but not send PMs. To send PMs your base rank has to be => 3 but to chat it checks your active rank. Like I said this isn't really an issue but it's kinda weird because both say that you need to be at least rank 3 but one can work when the other does not. So maybe a fix would be to make sending a PM check for active rank and not base rank, or make base rank 3 required to chat.

**Comment by bls1999** [comment]
#335 and #348 should fix this.

**Comment by Stxtics** [comment]
Fixed!
