### ISSUE TITLE
/clear crashes the server

### ISSUE THREAD

**Issue by bls1999** [jacob-grahn/platform-racing-2-server#34]
Not sure how to fix that...
@jacob-grahn

**Comment by jacob-grahn** [comment]
I made a quick patch, give it a go!

**Comment by bls1999** [comment]
It doesn't crash the server now, which is really good.
On the flip side, if it could clear everyone's chat immediately, that would be great.

**Comment by jacob-grahn** [comment]
Ah, right. I was trying to send a bunch of empty messages to clear the chat room, but it was only sending them to the user who sent the /clear command
