### ISSUE TITLE
Queries in the multiplayer_server

### ISSUE THREAD

**Issue by jacob-grahn** [jacob-grahn/platform-racing-2-server#341]
PDO doesn't support the kind of async queries that the multiplayer_server was using before. Solutions involving threads or forks seemed kind of complicated, so I decided to just use normal pdo queries and see if they really did introduce a noticeable amount of lag. The results seem to be great so far! 

Going forward: queries in the multiplayer_server are ok, but try not to use them often.

I'll close this issue in a bit. Just wanted to give a heads up.

Also, the PDOcalypse is completed! :earth_africa:

**Comment by bls1999** [comment]
What about setting `PDO::MYSQL_ATTR_USE_BUFFERED_QUERY` to false with requests from the multiplayer server?

https://stackoverflow.com/questions/27240421/php-asynchronous-mysql-query

**Comment by aaaaaa123456789** [comment]
That would help, although it would probably cause problems with concurrency. (You don't want to have to take a crash course in transaction isolation levels, trust me.)

It's better to just use queries that run fast. There's little need for the multiplayer server to use slow queries that require full table scans; make sure you have useful indices and check the query plans where necessary. A query like `SELECT * FROM <table> WHERE <column> = <value>` will run fast and cause no troubles as long as the column is indexed and the query returns a small number of rows. (Note that any query more specific than that will still run fast — DB engines are smart. `SELECT col1, col2 FROM table WHERE some_indexed_field = 20 ORDER BY something_else LIMIT 12, 6` will run fast as long as the number of rows returned without the `LIMIT` is reasonably small.)
