### ISSUE TITLE
pr2

### ISSUE THREAD

**Issue by Relokos** [jacob-grahn/platform-racing-2-server#342]
Hey jiggmin, can you go check your email jacob@grahn.io ? I emailed you something. Please reply on the email, not here.

**Comment by bls1999** [comment]
Please refer to README.md for acceptable things to post here. This is not an issue. He'll see it and respond when he's ready.

**Comment by Relokos** [comment]
Sorry, didn't think about that @bls1999

**Comment by jacob-grahn** [comment]
No problem, I got your message @Relokos
