### ISSUE TITLE
Add a few columns

### ISSUE THREAD

**Issue by bls1999** [jacob-grahn/platform-racing-2-server#343]
Hey @jacob-grahn, could you do me a favor and add a few columns?

 - `awarding` to the `contests` table, `varchar(255)`
 - `max_awards` to the `contests` table, `int(2)`
 - `awarded_by` to the `contest_winners` table, `int(11)`
 - `prizes_awarded` to the `contest_winners` table, `varchar(1000)`

Additionally, in the `contest_winners` table, could you change the name of `winner_name` to `winner_id` and change the type to `int(11)`?

Thanks, and sorry to bother you.

**Comment by Relokos** [comment]
I am curious, what is the contest table for?

**Comment by Stxtics** [comment]
@Relokos it's called a contest table, I wonder 🤔

**Comment by jacob-grahn** [comment]
Changes made!
