### ISSUE TITLE
[Suggestion] Spell-checking bot for commits?

### ISSUE THREAD

**Issue by bls1999** [jacob-grahn/platform-racing-2-server#351]
To prevent things like this (a trip down memory lane):

"Please refresh your browser to dowloand the new version."
"Hash don't match"
"thier"
"recieve"
"The save was succesful"

You can find all these hits and more on "Now that's what I call spelling" by @jacob-grahn :joy:

**Comment by aaaaaa123456789** [comment]
A spell-checking bot on a codebase will typically do more harm than good. Just review text before merging it in... it worked for me in a project that beats this one in amount of text by two orders of magnitude.

**Comment by bls1999** [comment]
@aaaaaa123456789 gotcha. Makes sense!
