### ISSUE TITLE
All-Time Best

### ISSUE THREAD

**Issue by bls1999** [jacob-grahn/platform-racing-2-server#358]
Did the process to find ATB levels change?  Lots of levels that meet the ATB criteria (i.e. Art Gallery by xXsuper3Xx with a 4.72 rating and Hat Factory with a 4.51 rating) are now gone, and the list is replaced by a lot of levels no one has ever heard of.

The top three levels of ATB currently are:
 - `Free Cowboy Hat` by `nico70`
 - `Free Crown Hat!` by `lp20`
 - `'Yoshi's Island'` by `Kooooooooool` (which is a copy of `Fire Shadow`'s Yoshi's Island level)

**Comment by Jmarroqu** [comment]
All-Time Best old maps got deleted months ago and were being replace with some of newest and today's best at least when I saw it. I thought Jiggmin made a changes of how to put it on ATB but maybe not? Also, can you @bls1999 not manually put back ATB by deleting/adding maps back to ATB? I'm not sure if that's something that you can or can't do.

**Comment by Stxtics** [comment]
There is also a level that I unpublished but is still in ATB

**Comment by bls1999** [comment]
@Jmarroqu it's automatic, so I can't manually add/delete maps.

**Comment by bls1999** [comment]
This has been fixed for a while. 🎉
