### ISSUE TITLE
Sending PMs is broken

### ISSUE THREAD

**Issue by bls1999** [jacob-grahn/platform-racing-2-server#362]
#348 has a query that I referenced in a newer pull.  The newer pull got merged without #348, causing an issue with sending PMs. @jacob-grahn

**Comment by SteelChivalry** [comment]
This is tactic to get more power and features.

**Comment by bls1999** [comment]
@Jmarroqu Good question!  Admins actually have some HTML tags enabled for them in PMs. That's why the welcome PM breaks when Jiggmin is a member; the `<a href=""></a>` tag is disabled for him, thereby creating a jumbled mess.

**Comment by EternalUF** [comment]
All fixed!

**Comment by bls1999** [comment]
Hooray!
