### ISSUE TITLE
Organizing Issues and Pull Requests

### ISSUE THREAD

**Issue by bls1999** [jacob-grahn/platform-racing-2-server#363]
Pulls Awaiting Merge:
 - #443, which adds checks to assorted files for a user being a Guest
 - #445, which removes fah db code

Unresolved Issues:
 - #250, Guests can't earn Kong badges (I'm working on this)
 - #358, All-time best has been replaced with a bunch of levels that are definitely not worthy
 - #387, Admin IP search crashes the entire server
 - #372, Spectator mode after forfeiting has a very slow refresh rate (see my comment).

Suggestions/Other:
 - #285, Suggests a fast botting prevention
 - #357, Asks for deletion of the top hat level entry in the `pr2_campaign` table
 - #388, Suggests custom error pages (instead of good ol' error #2032)
 - #409, Templocalypse
 - #446, Suggests being able to search for 3-character terms if within quotation marks

**Can be closed:**
 - #283

**Comment by aaaaaa123456789** [comment]
All of the pulls mentioned are merged and you can safely delete them from the list.

**Comment by bls1999** [comment]
Updated @jacob-grahn

**Comment by bls1999** [comment]
Making a new one
