### ISSUE TITLE
Guilds

### ISSUE THREAD

**Issue by Relokos** [jacob-grahn/platform-racing-2-server#364]
Everytime I view a guild, it gives me error #2032.

**Comment by bls1999** [comment]
Maybe that's because you're banned and you're not supposed to access it in the first place?  :thinking:

It's getting fixed.

**Comment by LP-PR2** [comment]
@bls1999 i'm banned and can still view guilds outside of pr2 🤔

**Comment by Jmarroqu** [comment]
@bls1999 Don't forget that discord bots can let's view/search things on Platform Racing 2 without going into the game :P

**Comment by woodenstix** [comment]
@bls1999 can you stop mindless hating against players?

**Comment by Relokos** [comment]
I used a bot to view the guild, never did I mention that I logged in.

**Comment by bls1999** [comment]
@Relokos seeing as you got "Error #2032" and that error is an ActionScript error, you definitely got it from the PR2 client.

**Comment by Relokos** [comment]
I didn't get it from the PR2 client.

**Comment by ShakeJunt01** [comment]
https://www.youtube.com/watch?v=RkZC7sqImaM

**Comment by BrokenBulb78** [comment]
Lol @Relokos why are you lying? Error #2032 is really an ActionScript error, https://pr2hub.com/guild_info.php wouldn't give that 🤔

**Comment by ShakeJunt01** [comment]
gewild

**Comment by Relokos** [comment]
@BrokenBulb78 I ain't lying, you're not a mod or anything like that so you wouldn't know.

**Comment by famelegend1** [comment]
you ain't lying, just like you never scammed, ey?

**Comment by bls1999** [comment]
Says the guy who ban evades, tries to view a guild on PR2, posts that he got "Error #2032" on pop-up, realizes he messed up, lies about not getting it on pop-up, and then proceeds to get roasted.  Only you, @Relokos.

Some resources:
 - https://stackoverflow.com/questions/6507461/error-2032-stream-error
 - https://owl.english.purdue.edu/owl/resource/659/03/ (see: red herring)

**Comment by woodenstix** [comment]
who cares if u b/e, everyone does it. get over it bls
