### ISSUE TITLE
Pr2 Staff

### ISSUE THREAD

**Issue by RealShadowZ** [jacob-grahn/platform-racing-2-server#365]
I refuse to join JV2 because I don't trust that website so I'll post what I have to say here

I was Shadow Z on Pr2. They always were my accs. I was always playing on them, then someone made a fake JV2 acc of me trying to recover my accounts and because Bls and Eternal scream JV2 they decided to recover them for the fake JV2 acc of me. I tried to get my accs back but because he used JV2 and I don't because I don't like the website he let him keep it. He said the decision was irreversible when I had very good proof that I was the original Shadow Z including emails locations and more. The other person didn't have any proof besides an email I posted to the public which was on my alt and he didn't know the original email on Shadow Z. And I was one of the best racers on pr2 when this fake JV2 acc of me isn't very good at racing so it's obvious that I was real all along because I've done so much over the few years of racing while this JV2 acc of me can't do anything

Now these staff think I'm recovering accs by impersonating even when they know I'm not and is just protecting a fake person on JV2 because he probably bribed them or did something because it really can't be any more obvious. Bls just bans people who aren't botting protects people who are botting because they are sucking up to him and Bls just wants power and attention because he's a suck up himself. Now I'm getting banned for no reason and I want to be unbanned as they are just playing favorites and listening to what haters have to say about me who are jealous about the accs I earned and made. Bls is trying to catch my accounts with the leaderboard so good luck because I have way too many accounts to go against this I'm not serving my ban for shit I haven't been doing it's all favoritism I tell you

**Comment by woodenstix** [comment]
you sure needed to make 2 accounts mate!

**Comment by Jmarroqu** [comment]
Even if this is true, why not just email Jiggmin and let him decide if your information is real enough to give the account back?

**Comment by EternalUF** [comment]
For the gazillionth time, this section of Github is for issues regarding the Platform Racing 2 Repo.

**Comment by ShakeJunt01** [comment]
this is a serious matter ( ͡° ͜ʖ ͡°)

**Comment by LP-PR2** [comment]
Gamebreaking issue.

**Comment by RealShadowZ** [comment]
@Jmarroqu Yeah I will I have way too much proof and Bls is just playing favorites probably because he has something against me or someone bribed him.

@EternalUF You were stupid enough to believe this fake JV2 acc of me so I don't want to hear it this is all favoritism

@woodenstix W8rnube this is my first Github account and I'm mad of this issue so I'm going to hammer away at the staff.

**Comment by bls1999** [comment]
@RealShadowZ give it a rest. I IP matched you with "Firefight", "Intrepid", and Zornified.  Unless all three managed to spoof their IPs to your residential one, there's no way you're innocent in this.

We went through a lot to confirm that the current owner of Shadow Z is the rightful one.  I'm sorry you don't like our ruling, but the notion that the evidence supporting his ownership is trivial is just false.

As for JV2, the actual Shadow Z did create a JV2 account to start an account recovery; However, @EternalUF and I followed up with both of you on discord starting from scratch.  If you recall, we went through painstaking measures to verify your claims against Shadow Z's claims.  We ultimately determined that the other user was the rightful owner and returned his account to him.

That's it.  You want transparency, you got it.  Don't cry "corruption" where there isn't any.

**Comment by LP-PR2** [comment]
Your English is pretty good considering you're Swedish.

**Comment by RealShadowZ** [comment]
I'm the real Shadow Z because that fake JV2 acc of me isn't as good of a racer as me and doesn't have the proof that I have and I was always good at racing since JV times in 2011 up to 2017 and even now while this fake JV2 acc of me sucks and can't impersonate my racing skills. Firefight is the real one because he was also good at racing. Bls you don't know which you are talking about so you should probably give me my Shadow Z account back sooner rather than later because it was my account. This situation was so bad I had to add [Real] to my name because it was confusing on Discord with two Shadow Zs one saying they were original and then there was me the real original owner so I added Real to make a distinction between us two and to show it was me buy people don't really understand that because they are believing the lies and baloney you are saying and the favoritism. Your staff are probably paying for staff here now because you need money to run JV2 Hahahah like why is Eternal admin when he was helping Dark Player an impersonator who framed people on his stupid Supi accounts and why is Rigby mod when he has scammed people before and helped people hack accounts he had hacked someone's email before for an account and why is a7x3 mod he is just protecting his e-girl Sindel who has been flaming Vipa but she doesn't get banned Vipa gets banned so it's all unfair. It's all favoritism and money now this admin must be demoted and all of his cronies in staff

**Comment by RealShadowZ** [comment]
Also this fake JV2 acc of me modified my level Pitfall Valley in intention of ruining the GGP contest so it's obviously not the real one because I'm the real one

**Comment by bls1999** [comment]
@RealShadowZ modified his* level Pitfall Valley, without knowledge it was being used in GGP.*

**Comment by RealShadowZ** [comment]
It's my level don't try to hide yourself Bls are you too coward to respond to the reality in my post

**Comment by bls1999** [comment]
@RealShadowZ It's his* level, and I won't be responding to the relentless lying* in your post.  Give it a rest.

**Comment by Jmarroqu** [comment]
in before I post a thread on github, check discord @bls1999 pr2 disc

**Comment by RealShadowZ** [comment]
See he's protecting the fake JV2 acc of me just give me my account back I have other accounts to play on from the people that know I'm real and not fake but Shadow Z is my precious account so you give it a rest and do it

**Comment by bls1999** [comment]
So enlighten me @RealShadowZ. Why was your IP on Firebird, Intrepid, Zornified, and Shadow Z?

**Comment by Jmarroqu** [comment]
Firefight * @bls1999

**Comment by RealShadowZ** [comment]
Why does colind have his ip on Alphas accounts because he has access to them is he AlphaZ no

My IP isn't on any of those accs but people can have access to accounts so you lose again and I'm winning badly I'm getting my accounts back

**Comment by Jmarroqu** [comment]
My IP hasn't been on AlphaZ in forever, lmao.

**Comment by bls1999** [comment]
> you lose again and I'm winning badly I'm getting my accounts back

Except you're not winning because this isn't up for discussion, and you're not getting someone else's accounts returned to you.

**Comment by RealShadowZ** [comment]
You're not returning them I'm getting Jiggmin too because you're too stubborn to see the proof

**Comment by Jmarroqu** [comment]
Jiggmin isn't gonna read this and side with you, he's going to ask the Staff if he cares enough to deal with your problem. My advise, email him and end this issue.

**Comment by bls1999** [comment]
@RealShadowZ good luck with that

**Comment by Jmarroqu** [comment]
@bls1999 How long is your Admin tool IP's history? 50 slots big or give or take a few from that number?

**Comment by bls1999** [comment]
I made a tool that can see all logins from an account since approximately May 28, 2013. @Jmarroqu

**Comment by Jmarroqu** [comment]
Can Jiggmin see these logs as well if he choose to? @bls1999

**Comment by bls1999** [comment]
@Jmarroqu yep

**Comment by ShakeJunt01** [comment]
@bls1999 when was the last time I logged in before I came back, I'm really curious about it uhu

**Comment by bls1999** [comment]
DM'd it to ya @ShakeJunt01

**Comment by bls1999** [comment]
@Jmarroqu seems legit

**Comment by ShakeJunt01** [comment]
@bls1999 I want my email switch on your account, if I ask gently I'm pretty sure it's possible ( ͡° ͜ʖ ͡°) Pretty please

**Comment by BrokenBulb78** [comment]
hi im real shadow z because im better at racing than him so please please switch muh email

**Comment by RealShadowZ** [comment]
Racing skill can't really be impersonated you know. For example fake 898 or fake Vipa would be easy to find if they are playing like noob.

**Comment by RealShadowZ** [comment]
I mean why doesn't that apply to me I have always been good and no one ever says fake 898 or anything but he could be fake because racing skill can be impersonated according to you but he's always been good and can prove he's real. I've always been good and I can prove I'm real too

**Comment by LP-PR2** [comment]
https://i.imgur.com/GmOWq8n.png
https://i.imgur.com/oXCJczr.png

Interesting...

**Comment by ShakeJunt01** [comment]
@RealShadowZ The Z we have rn (and the REAL REAL REAL one because I knew him since the start of the game so huh) is really good and even of the best racer I know in this game so I'd ask you to please stop saying you're ''better'' than him at racing

**Comment by RealShadowZ** [comment]
@ShakeJunt01 You're talking about the fake JV2 acc of me. No he is not better than me at racing. Can he get 1:28 on Obstacle Course or 1:29 on Lightspeed 2 or 31 seconds on Yoshis Island or 26 seconds on Candyland? No that's too pro for the fake JV2 acc of me and this all except the last one is without real glitches lmao

**Comment by ShakeJunt01** [comment]
@RealShadowZ Nope I'm talking about the Z I've been racing on Pr2 for a long long time, you don't even know me and it's proof enough that you aren't [Real]

**Comment by RealShadowZ** [comment]
You never knew me and you're just making lies to protect the fake JV2 acc of me, or maybe you're him

**Comment by RealShadowZ** [comment]
http://prntscr.com/j1jlg4
http://prntscr.com/j1jlub

6:05 on The Legend first try with rank 41 stats. I don't think this Fake JV2 guy can pull this off which shows I'm real. I don't need to give any more proof it's all just bribery

**Comment by ShakeJunt01** [comment]
you're right I don't know you and yeah I'm pretty much impersonating myself I'm doing a good job don't you think?

**Comment by ShakeJunt01** [comment]
@RealShadowZ why are you hiding your name on both of them lol

**Comment by famelegend1** [comment]
this is freaking hilarious but pathetic at the same time. i especially like how you say racing skill can't be impersonated, but you were caught impersonating firefight's racing skill? nice one. you're not getting "your" accounts back... you've already shown that you are definitely NOT the original shadow z, so put an end to this. but i'm not going to get much into this anyway because i'm caught up with stuff and this isn't your place to rant.

**Comment by woodenstix** [comment]
@RealShadowZ stop using my records just because i did those on ur accs, plz

**Comment by ShakeJunt01** [comment]
all we have to do is give peace a chance, look I'm impersonating John Lennon right now because I'm John Lennon [Real]

**Comment by LP-PR2** [comment]
I love how my screenshots that disproved everything this guy is saying were ignored and he's still requesting proof.. i'll just repost them

https://i.imgur.com/GmOWq8n.png
https://i.imgur.com/oXCJczr.png
