### ISSUE TITLE
One more column

### ISSUE THREAD

**Issue by bls1999** [jacob-grahn/platform-racing-2-server#370]
@jacob-grahn Can you add `awarder_ip` to `contest_winners`? `varchar(100)` should suffice. This is it, I promise!

**Comment by Relokos** [comment]
bls can i talk to you regarding an issue, ofc nothing to do with me. do you have an email where i can contact you

**Comment by bls1999** [comment]
My email is bls1999@jiggmin2.com. Please keep issues on github on-topic.

**Comment by jacob-grahn** [comment]
Done!

**Comment by bls1999** [comment]
Thank you!  Hopefully everything works as intended. 🙏🏻
