### ISSUE TITLE
Lol

### ISSUE THREAD

**Issue by FirefightPR2** [jacob-grahn/platform-racing-2-server#379]
It is possible to access accounts just with the email. Good luck fixing it.

**Comment by Stxtics** [comment]
Remove all accounts emails ez fix

**Comment by famelegend1** [comment]
![](https://cdn.discordapp.com/attachments/425056288448446464/427631796314832896/ARETA.jpg)

Pretty much everyone smart knows you wrote on the wrong account

**Comment by ShakeJunt01** [comment]
I'm honestly scared because I've been getting email changes on $hake Junt and I didn't tell anyone my pass @BrokenBulb78 @bls1999
