### ISSUE TITLE
Custom Error Pages

### ISSUE THREAD

**Issue by bls1999** [jacob-grahn/platform-racing-2-server#388]
https://www.digitalocean.com/community/tutorials/how-to-configure-nginx-to-use-custom-error-pages-on-ubuntu-14-04

I think it would be cool if we could make error pages that don't make the client throw error #2032.

**Comment by jacob-grahn** [comment]
Good old `#2032` has been around for _so long_ that I feel kind of attached to it :stuck_out_tongue_winking_eye: 

Some kind of message like `The web page could not load` would probably be more useful, though.

**Comment by bls1999** [comment]
@jacob-grahn would the game always pop up a message if the return data was `message=` or `{"message":"blah"}`, or does it matter which script sends what data?

**Comment by bls1999** [comment]
I can do this client-side
