### ISSUE TITLE
URGENT FIX

### ISSUE THREAD

**Issue by EternalUF** [jacob-grahn/platform-racing-2-server#393]
Typing in-game race chat crashes the server :/

**Comment by BrokenBulb78** [comment]
Ahha, that's why I couldn't chat in levels yesterday

**Comment by woodenstix** [comment]
how about you call some people cancer again man
you know what im talking about

**Comment by BrokenBulb78** [comment]
https://cdn.discordapp.com/attachments/249678944956055562/433649173418737664/backtick.webm
It looks like the server crashes when you type `chat``.

**Comment by bls1999** [comment]
@EternalUF @jacob-grahn #395

**Comment by EternalUF** [comment]
Woo!
