### ISSUE TITLE
[Not Urgent] problem with setting user status

### ISSUE THREAD

**Issue by bls1999** [jacob-grahn/platform-racing-2-server#4]
Problem with server/Player.php, line 776

This does not check if a player is connected to another server.  It sets them offline, but it also doesn't update if the player is on another server.  This causes a player to appear offline if they log into two servers and log out of the most recently logged into one.

Example:
 - Bob logs into Derron, game sets his status to Derron
 - Bob opens a new tab and logs into Carina, game sets his status to Carina
 - Bob logs out of Carina, game sets his status to offline
 - Bob is still on Derron, game doesn't update his status.

This isn't urgent, but it's something that could be fixed.  Perhaps a check for online instances every minute or so would be useful?

**Comment by aaaaaa123456789** [comment]
A better solution would simply be to track the list of servers the player is in, and only display "offline" when that list is empty.

**Comment by jacob-grahn** [comment]
I don't really intend to fix this one, so I'm going to close it for now.
