### ISSUE TITLE
Servers not saving data

### ISSUE THREAD

**Issue by EternalUF** [jacob-grahn/platform-racing-2-server#40]
It appears the servers (possibly with the exception of Isabel) aren't saving data, which means parts revert when you log out and Welcome exp is given after each login. I would assume because of the new phps on Isabel, its causing issues on the other servers?

**Comment by jacob-grahn** [comment]
I'm guessing the new code was opening connections to the db and never closing them, so eventually the db started refusing new connections. I patched that and restarted the servers, we'll see if that fixes it.

**Comment by EternalUF** [comment]
From the first glance everything appears to be workings fine, I tested those two known issues stated above, and those seem to be working fine. Thank you for pushing those updates to all servers! :D
