### ISSUE TITLE
Bugs existing post-Lint

### ISSUE THREAD

**Issue by bls1999** [jacob-grahn/platform-racing-2-server#402]
@jacob-grahn The lint branch looks great!  I have just a few things I want to point out.  Some of these are existing bugs that I never got around to reporting.

1. Lint removed these crucial global calls inside functions:
 - [Line 106](https://github.com/jacob-grahn/platform-racing-2-server/compare/lint#diff-d9e7b5ed4b6e7ec7d851d4d6f499001fL106) in `http_server/www/admin/contests/add_prize.php`
 - [Line 127](https://github.com/jacob-grahn/platform-racing-2-server/compare/lint#diff-56b64fd8cd5b048cf4762d57cbe5a0c6L127) in `http_server/www/admin/contests/remove_prize.php`
 - [Line 256](https://github.com/jacob-grahn/platform-racing-2-server/compare/lint#diff-d7a77ff48277e416717aa82a24644134L256) in `http_server/www/contests/award_prize.php`
2. Does the `socketDaemon` code belong in `vend`?  Could it be run directly out of the `policy_server` folder?  I don't think we need duplicates of those files, unless I'm missing something?  If for some reason we do need duplicate code, could we put it in a shared folder with `policy_server`?
3. Could we move queries to the repo's root directory, since they're used by both `multiplayer_server` and `http_server`?
4. The loiter detector has been broken, but this update _might_ fix it.
5. Failover servers is broken due to a syntax error on line [16](https://github.com/jacob-grahn/platform-racing-2-server/blob/424027fadb88d56a21b9ebd0f0493033c231bed9/http_server/queries/servers/server_update_address.php#L16) in `http_server/queries/servers/server_update_address.php`
6. Some strings are split in random places due to the auto-format to PSR-2 (like Lines [613](https://github.com/jacob-grahn/platform-racing-2-server/compare/lint#diff-57e74c59a4d841ad24ae13dfcb94f2c1R613) to [622](https://github.com/jacob-grahn/platform-racing-2-server/compare/lint#diff-57e74c59a4d841ad24ae13dfcb94f2c1R622) in Player.php).  Could we possibly fix that?
7. PR2Client.php is a sort of misleading name (i.e. we have client code and server code); could it be named PR2ServerClient.php or something to that effect?  This is more of a housekeeping thing than anything.
8. `get_record()` was removed from [`multiplayer_server/rooms/ChatRoom.php`](https://github.com/jacob-grahn/platform-racing-2-server/compare/lint#diff-0d7fcb4c3e85d8d44ab7c77ab8ea7bc2L82), possibly causing issues with getting the existing chat array?
9. Line [888](https://github.com/jacob-grahn/platform-racing-2-server/compare/lint#diff-69b88c4d33253b79c2bd446afee748a2R888) in `multiplayer_server/rooms/Game.php` should probably be changed to
``$player->socket->write("chat`$name`$power`$text");`` just to be safe.
10. Just a personal question: where is `namespace pr2\multi;` defined? I've never worked with namespaces, so I'm just trying to further my own knowledge.

Personal To-Do: On line [437](https://github.com/jacob-grahn/platform-racing-2-server/compare/lint#diff-69b88c4d33253b79c2bd446afee748a2R437) in `multiplayer_server/rooms/Game.php`, create another variable to be passed that will determine the number of digits to which to round.

**Comment by LP-PR2** [comment]
Yes

**Comment by bls1999** [comment]
@LP-PR2 1:01 https://www.youtube.com/watch?v=dFre0ncUY64&feature=youtu.be&t=1m1s

**Comment by jacob-grahn** [comment]
1. My bad, the linter thought the variables were unused. My general goal is to get the linter to stop complaining about things, so we'll probably need set up a switch statement or something.

2. Both the multiplayer_server and the policy_server will use the code from vend/server. A common standard is to store code written by other people/companies in a vendor folder, and the vendor folder shouldn't be checked into the repo. Instead, the project should contain instructions on how to install the code from the outside vendors. The `socketDaemon` code is quite old and I have made small modifications to it over the years, so I'm cheating a bit by sticking it in the vend folder and checking it into the repo.

3. Could do

4. Cool!

5. Oh, those periods..

6. For now I'm just trying to get all of the errors here to go away: https://travis-ci.org/jacob-grahn/platform-racing-2-server
We can do whatever as long as the line length stays under 120.

7. Sure!

8. get_record didn't appear to be used anywhere

9. Sure, why not?

10. It's not defined anywhere, it's more like putting the code in a virtual folder. If your working with code from multiple projects, it helps prevent situations where two different projects have used the same class name for something.

**Comment by jacob-grahn** [comment]
I just merged the lint branch into master. There may still be bugs! If there are, open some new tickets to track them.
