### ISSUE TITLE
Depreciated tables/database changes

### ISSUE THREAD

**Issue by bls1999** [jacob-grahn/platform-racing-2-server#408]
The following tables in the database no longer have any use:

 - `bounce` - was used to store Volly-Bounce data
 - `failed_captchas` - was used to store failed cat captchas
 - `lux_today` - used to track lux gain
 - `lux_total` - used to track lux gain
 - `promotion_log` - while it's actively added to, we have the admin log which records the same thing. You can decide if you think this is still needed.

The following tables in the database no longer have an ostensible use (basically, I could be missing something, but I believe thse aren't used anywhere anymore):
 - `guilds_newer` - an unused table
 - `domains` - an old table used to keep track of allowed domains
 - `flagged_messages` - an old version of the `reported_messages` table
 - `queries` - I assume this is related to the stored database procedures that were converted to PDO
 - `users_new` - an old table used to keep track of new users... but no data is ever retrieved

Additionally, please run these queries:
```mysql
ALTER TABLE `recent_logins` MODIFY `ip` varchar(100) NOT NULL; /* change from 30 to 100 chars */
ALTER TABLE `contests`
  MODIFY `awarding` varchar(255) NOT NULL,
  MODIFY `max_awards` int(2) NOT NULL; /* sync contests table with my localhost */
```

**Comment by jacob-grahn** [comment]
Thanks for weeding through all of the tables. That's quite a chore :open_mouth:

**Comment by jacob-grahn** [comment]
Table alterations complete!
