### ISSUE TITLE
Templocalypse

### ISSUE THREAD

**Issue by jacob-grahn** [jacob-grahn/platform-racing-2-server#409]
First came the PDOcalypse
Then came the Lintocalypse

Now it's time to bring in the Templocalypse! The goal will be to separate pr2's logic (php) from presentation (html)

Most template engines will also automatically escape data, so there's a security perk on top of cleaning up some tangled code.

The only template engnine I've used with php is [Plates](http://platesphp.com/). If anyone has a preference or experience with another templating engine, I'd love to hear about it.

**Comment by bls1999** [comment]
@jacob-grahn I'm concerned about people (including me) having to learn how to correctly write in the template engine's language.  I'm also concerned that Travis might create some false positives.

**Comment by bls1999** [comment]
I'm gonna go ahead and assume this ain't happening.
