### ISSUE TITLE
Logging out does not work correctly

### ISSUE THREAD

**Issue by Stxtics** [jacob-grahn/platform-racing-2-server#416]
This might be fixed now because of #413 as it may have been caused by #399 . But basically when you logout your account stays online in the online list even though you are not on it. If you try to login again it will say you were already logged in, then after that you can log back in. This is probably fixed now but I'm posting this just in case.

**Comment by EternalUF** [comment]
I still have this issue

**Comment by woodenstix** [comment]
how do you fuck up this badly

**Comment by bls1999** [comment]
I think it has to do with lint @jacob-grahn

**Comment by woodenstix** [comment]
faggot scum stop deleting my messages

**Comment by bls1999** [comment]
@woodenstix your words are disgusting and uncalled for. You should be ashamed of the way you're treating others.

**Comment by Stxtics** [comment]
Fixed!
