### ISSUE TITLE
Admins' server restarts

### ISSUE THREAD

**Issue by bls1999** [jacob-grahn/platform-racing-2-server#425]
For some reason, it seems that any server after Morgana on the list (Andres, Isabel, Tournament, Fred, untested on Gods of Glory) is unable to be restarted using the `/restart_server` chat command for admins.

**Comment by Jmarroqu** [comment]
I will let AlphaZ know to know if that works in GOG

**Comment by bls1999** [comment]
This... seems to be fixed.
