### ISSUE TITLE
GP Today

### ISSUE THREAD

**Issue by Stxtics** [jacob-grahn/platform-racing-2-server#431]
GP Today doesn't reset everyday, I've had 6 GP today for 3 days now. I'm guessing this is because the servers only restart weekly now but its called GP Today not GP this Week ;)

**Comment by famelegend1** [comment]
don't think it has to do with server reset. before the gp reset slightly before the server restarted (by about 2 hours OTOH)

**Comment by bls1999** [comment]
I know why this is happening; I'll fix it.
