### ISSUE TITLE
fix user_new and also user_select_expanded

### ISSUE THREAD

**Issue by joseph12311** [jacob-grahn/platform-racing-2-server#432]
when you try and create a new account on pr2 it said could not insert new user into new_user

Yup

and when you invite somebody to a guild it sais user_select_expanded

**Comment by bls1999** [comment]
#434 will fix this.

**Comment by jacob-grahn** [comment]
@joseph12311 Are the issues fixed on your end?

**Comment by EternalUF** [comment]
Creating new accounts is working fine now
