### ISSUE TITLE
Name changes = lose tokens.

### ISSUE THREAD

**Issue by Stxtics** [jacob-grahn/platform-racing-2-server#439]
I think I remember seeing about something getting removed with f@h but I logged on my account Suppression today which had 4 tokens and now it only has 3. https://i.imgur.com/sKtnxte.png From that screenshots you can see I have 12 hats. I got PMs about getting +3 tokens as suppression only has 90k f@h. So I think the cause of this it removed my 4th token but not my cowboy weirdly.

EDIT: Also a lot of users are getting PMs about stuff they already had.

**Comment by EternalUF** [comment]
According to the updated admin tools, which bls just merged for FAH information, it appears Suppression has r1-r4, but like he said the available tokens on the account is three. Odd.

**Comment by Rebuked** [comment]
[http://prntscr.com/j9pkd8]

Just got 5 messages from Jiggmin so F@H also works for account with history of Name Changes!

So this means @jacob-grahn  applied @bls1999 scripts.

**Comment by bls1999** [comment]
The reason people are getting PMs about stuff they've already had is because presumably Jiggmin truncated the stats table.  LMK if it continues.

**Comment by bls1999** [comment]
@Stxtics I just copied your account from PR2 to my localhost. It seems that with the next FAH update you'll get the 4th token. I'm not sure why it hasn't updated yet.

**Comment by Stxtics** [comment]
Suppression is getting 5th anyway but does this mean I wouldn't of got my 4th back if it wasn't getting folded? I'm not sure if anyone else was affected by this but there could be a few accounts that were.

**Comment by bls1999** [comment]
@Stxtics `fah_award_prizes.php` doesn't remove any tokens.

**Comment by Stxtics** [comment]
Weird, anyway I just logged on and I have my 4th again.

**Comment by bls1999** [comment]
yep, it looks like the stats just updated.
