### ISSUE TITLE
VOM issues

### ISSUE THREAD

**Issue by EternalUF** [jacob-grahn/platform-racing-2-server#440]
I've been hearing VOM is giving errors again, looks like buying rank tokens give the whole "there was an error while contacting the game server to finalize your order, blah blah"

**Comment by Rebuked** [comment]
https://youtu.be/rFm3fGUkj2I

Here's proof.

**Comment by bls1999** [comment]
Kong actually says "blah blah???" Lol

But yeah, there's an error saying Kong can't contact PR2's servers to complete the transaction.

**Comment by EternalUF** [comment]
All fixed, thank you @jacob-grahn!!
