### ISSUE TITLE
Socket Server: Things that aren't/might not be needed, suggested changes

### ISSUE THREAD

**Issue by bls1999** [jacob-grahn/platform-racing-2-server#458]
Things that don't seem to be used anywhere in the code:
 - `multiplayer_server/fns/data_fns.php`:
   - `function get($str, $default)`, Lines 4-12
   - `function find_variable($string, $default)`, Lines 16-27
   - `function remove_resource($_target)`, Lines 94-134
   - `function get_user_dir($user_id)`, Lines 182-196
 - `multiplayer_server/fns/utils.php`:
   - `function get_banned_ip($ip)`, Lines 71-86
 - `multiplayer_server/process/send_message_to_player.php` (entire file)

Suggested changes (root = root of repo):
 - Move manage folder from `multiplayer_server` to new folder in root called `manage_multi`
 - Move `queries` from `http_server` to root
 - Organize all `http_server` functions into subfolders within the `fns` folder

I can get some of this started with a pull or two if you're game. @jacob-grahn

**Comment by jacob-grahn** [comment]
That all looks good to me!

**Comment by bls1999** [comment]
I'll call it… organipocalypse! :joy:

**Comment by bls1999** [comment]
The socket server portion of the organipocalypse is done!
