### ISSUE TITLE
users_select_top

### ISSUE THREAD

**Issue by bls1999** [jacob-grahn/platform-racing-2-server#462]
@jacob-grahn 

Could you do me a favor and run this database query, and then let me know how long it took?  I'm trying to see if this is a viable alternative to the current `users_select_top` function we have now.

```mysql
        SELECT u.name AS name,
               u.power AS power,
               SUM(IFNULL(rt.used_tokens, 0) + pr2.rank) AS active_rank,
               pr2.hat_array AS hats
          FROM users u
          LEFT JOIN pr2 ON pr2.user_id = u.user_id
          LEFT JOIN rank_tokens rt ON rt.user_id = pr2.user_id
         GROUP BY name, power, pr2.rank, rt.used_tokens, hats
        HAVING active_rank > 49
         ORDER BY active_rank DESC, name ASC
         LIMIT 0, 100
```

I'm thinking that the limit would prevent the db from overloading itself.  The query worked fine on my localhost, but I can't test query times against the insane amount of data you must have in the entire PR2 database, after literally 10 years of data collection.

If the retrieval time is less than ideal, maybe indexing the `rank` column in the `pr2` table and/or the `used_tokens` column in the `rank_tokens` table would help?

**Comment by isokissa3** [comment]
The query is still going to look thru every row in all tables, the most proper way to do this would be cache the results for like 15mins and regenerate when it has expired

Also assuming that all those tables are simple and can be held in memory easily providing fast read speeds

**Comment by bls1999** [comment]
@jacob-grahn

**Comment by BrokenBulb78** [comment]
@jacob-grahn
