### ISSUE TITLE
Rank tokens aren’t separate 

### ISSUE THREAD

**Issue by EternalUF** [jacob-grahn/platform-racing-2-server#466]
The pr2 staff guild has a rented rank token. So I have 5 tokens from FAH and that one extra token. I’m getting “Too many tokens, please use another account”

**Comment by EternalUF** [comment]
Still an issue

**Comment by bls1999** [comment]
I just moved out of my college dorm today for the summer.  I'm very very tired, so I'll look at this tomorrow.

**Comment by jacob-grahn** [comment]
Did splitting up the rank token check here not fix the problem? https://github.com/jacob-grahn/platform-racing-2-server/blob/7ee614ef9a4db37e24eface75c4af7ec49d57922/http_server/www/login.php#L181

**Comment by famelegend1** [comment]
it doesnt seem to distinguish actual f@h rank tokens from guild tokens yet. im not sure exactly why though.

**Comment by bls1999** [comment]
@jacob-grahn I made a boo-boo and included `$rt_used` in that check. It should be fixed in #471.
