### ISSUE TITLE
/hh command does not work correctly.

### ISSUE THREAD

**Issue by Stxtics** [jacob-grahn/platform-racing-2-server#474]
![image](https://user-images.githubusercontent.com/18367146/39769493-48591898-52e4-11e8-8bba-dba8cc9c3b34.png)
This screenshot was took 19 minutes into the happy hour and it says there is -94214 seconds left on the happy hour which is -1570.2333 minutes. 
(Happy hours still do last an hour if anyone was confused)

Also seeing as now there is only 5 non guild servers instead of 9 that can have a happy hour on them shouldn't the chance of a happy hour be increased?

**Comment by bls1999** [comment]
#479

**Comment by Stxtics** [comment]
Alright and this was taken 3 minute into a happy hour. 
![image](https://user-images.githubusercontent.com/18367146/39928167-8303d114-552c-11e8-94e8-b3ed55b8315c.png)

**Comment by Stxtics** [comment]
Ok I think this command seems to only work in the last 30 minutes of a happy hour. I did it earlier today and it said 35 minutes left, however I just did it now after a happy hour just started and it shows this 
![image](https://user-images.githubusercontent.com/18367146/40085856-e19be7ce-5893-11e8-9dc9-433c41128388.png)

**Comment by bls1999** [comment]
I always use it right after activating to make sure it worked, and it never tells me there's an issue.  Maybe it has to do with manually-activated happy hours as opposed to random_hour.  I'll do some investigating.

**Comment by bls1999** [comment]
@Stxtics is this still happening?

**Comment by Stxtics** [comment]
I havent tried yet but i will when i next can

**Comment by Stxtics** [comment]
![image](https://user-images.githubusercontent.com/18367146/40500762-b16e57f8-5f7d-11e8-8fb1-7aea56969e28.png)

still happening
