### ISSUE TITLE
rodent precautionary measures?

### ISSUE THREAD

**Issue by famelegend1** [jacob-grahn/platform-racing-2-server#477]
what else can we do? we've already made an extra sanity check that checks hat bonus, rank used in race, amount of tokens, but i feel we are still missing stuff... Thoughts? @bls1999 @BrokenBulb78 @Dex472

**Comment by Dex472** [comment]
I don't think this is the place to fight over things.

**Comment by bls1999** [comment]
I'd say just going through all of the DB tables and making sure the methods used to communicate with those tables are secure.

**Comment by famelegend1** [comment]
@bls1999 maybe checking request method and making sure its from post or from a trusted ref?

**Comment by famelegend1** [comment]
@bls1999 maybe one thing for staff accounts, when they are logging in from a new IP, they have to click a verification link in order to authorize their token in their email? what do you think? could see this being a boost in security.

@aaaaaa123456789 @jacob-grahn thoughts?

**Comment by Altex1** [comment]
@famelegend1 That's pretty good idea, that would prevent keylogging mod/admin accounts aswell.

**Comment by isokissa3** [comment]
Or you could use 2FA which is less anonying in my opinion, email sometimes likes to take a while to pop up etc.

This could be achieved by entering your 2FA in the username in special format, for example isokissa3@333333 or more anonying way; enter username and pass first and after that it requests the 2FA code to be entered by keeping track of the state in the server

**Comment by FearlessFlare** [comment]
This is some laughable ass kissing from @famelegend1. You're creating BS problems in your daydreams in hope of attention on here. There's never been a speck close to a problem in your pull requests. All you've contributed to this repository is useless if statements that are rendered useless by the rest of this server code. Given that you and these staff clowns just want attention, there's no wonder that they are all in awe over this filthy pig snot that you've created. That's the reality of this entire romance game you simpletons are playing. Open your eyes and realize the truth for damn sake.

In addition, you and the other novelty-toothed nincompoop staff have been dreaming and believing what you want to believe, not the reality. You keep moaning and jabbering about "rodents" and other gibberish along these lines, but where is the proof to all of this? I'll give your food crumb sized brains time to comprehend this, while I already know the answer. Guess what? You thick burritos don't have any proof whatsoever, and you guys are simply weighing innocent people's reputations down below sea level with your pathetic framing attempts. Put it aside and see my side.

**Comment by aaaaaa123456789** [comment]
That many insults in a message? Come on, you can post a useless rant with more class. Let's try again, from... hm, "rendered useless by the rest of this server code."

**Comment by famelegend1** [comment]
"All you've contributed to this repository is useless if statements" -- well i prevented you rodents from logging into your token-stashed accounts, so it's not useless. pls stop daydreaming

**Comment by bls1999** [comment]
@FearlessFlare you invalidate your arguments by:
 - Creating new GitHub accounts just to attack us
 - Using ad hominem attacks instead of explaining your side in a civilized manner
 - Not offering any helpful alternative advice to what you claim is an issue

I'll tell you what I told you in #484: If you don't have anything productive to contribute to the conversation, please refrain from posting.

**Comment by BrokenBulb78** [comment]
Ayy that's a great idea! @famelegend1

**Comment by famelegend1** [comment]
honestly @aaaaaa123456789 @bls1999 i wonder if you can even classify this stuff as insults. it made me laugh so hard that i had to catch my breath, wbu guys
