### ISSUE TITLE
Fred and Isabel down

### ISSUE THREAD

**Issue by Stxtics** [jacob-grahn/platform-racing-2-server#481]
Since the most recent pull requests were added Fred and Isabel have been down.

**Comment by bls1999** [comment]
I know what this is about. Since I moved the `/multiplayer_server/manage/` folder to `/common/`, the cron to restart the servers that are down is messed up.  I can add that to minute.php.

**Comment by bls1999** [comment]
#483 is a temporary fix while I continue the organipocalypse.
