### ISSUE TITLE
A few issues

### ISSUE THREAD

**Issue by EternalUF** [jacob-grahn/platform-racing-2-server#49]
- Lifting and editing bans show "File not found."
- Player searching (as Moderator) returns "referrer is: http://pr2hub.com/mod/player_search.php" for any input **DONE**
- Artifact seemed to not award bubble to the user that found it first, and **every** user who finds and finishes with the artifact hat receives: http://prntscr.com/i28w0f
- Isabel is down :(
**- Bans aren't initiating server side**
- Cat/dog test isn't displaying pictures but seems to be able to answer correctly if you guess right. Could be due to user connection or slow response time from servers? 
-Error 2032 when doing "Forget password"

Couple issues I've not been able to test:
- I heard something's wrong where clicking to submit pass on password protected levels aren't registering? Haven't been able to test this.

**Comment by Antonhs30000** [comment]
Interesting.

**Comment by jacob-grahn** [comment]
Most of these are from my moving some things to a different server to better handle the DDoS attacks. I'll get the server configs sorted out slowly but surely...

**Comment by jacob-grahn** [comment]
Is the "referrer is: http://pr2hub.com/mod/player_search.php" problem fixed?

**Comment by bls1999** [comment]
@jacob-grahn yes!

**Comment by EternalUF** [comment]
Added and edited issues :p

**Comment by EternalUF** [comment]
Added some more, would you rather me make separate issues for all these?

**Comment by EternalUF** [comment]
Going to close this and make smaller issues, this is a headache to see.
