### ISSUE TITLE
Folding at Home pt. 10002383045834905

### ISSUE THREAD

**Issue by EternalUF** [jacob-grahn/platform-racing-2-server#490]
FAH seems to be acting up AGAIN, darn tabs (FAH).

**Comment by bls1999** [comment]
My bet is the minute CRON isn't working properly. Newest and server statuses apparently aren't updating either. I'll look into what could be causing it.

**Comment by famelegend1** [comment]
the issue regarding fah is different every time, legit

**Comment by bls1999** [comment]
It fixed

**Comment by EternalUF** [comment]
Woooo!
