### ISSUE TITLE
forgot password not working

### ISSUE THREAD

**Issue by famelegend1** [jacob-grahn/platform-racing-2-server#492]
*secretly trying to make malicious pull request*

if you enter any email you'll get this error:

Error: "" is not a valid email address.

does this have to do with the removal of die()? but it also seems like this line was removed:

line 15: $email = filter_var($_POST['email'], FILTER_SANITIZE_EMAIL);

**Comment by bls1999** [comment]
`valid_email()` already checks with `filter_var()`, so that check was redundant. Let me check what's being passed to the script.

**Comment by famelegend1** [comment]
yeah i think it might have to do with die() but who knows.

**Comment by bls1999** [comment]
Fixed in #493
