### ISSUE TITLE
[Suggestion] Mute command

### ISSUE THREAD

**Issue by BrokenBulb78** [jacob-grahn/platform-racing-2-server#494]
Muting players would be a great feature for PR2! For situations in chat, the player will get muted, but for situations like hacking, etc. the player will get banned instead. I clearly have no idea how can this be added though. :joy: @bls1999 @jacob-grahn

**Comment by bls1999** [comment]
Hey Anton, can you post this in the PR2 Suggestions section on JV2?

**Comment by famelegend1** [comment]
i guess you could reuse some of the code that is used to warn people, right?

**Comment by BrokenBulb78** [comment]
Yeah, you're right. My bad!
