### ISSUE TITLE
Server issues

### ISSUE THREAD

**Issue by EternalUF** [jacob-grahn/platform-racing-2-server#496]
All servers except Carina and Grayson are down.. Not sure why. It says there are people on, but the minute CRON and all of the other CRONS are messed up so the server status isn’t updating

**Comment by bls1999** [comment]
I tested everything and it worked fine. @jacob-grahn are my changes pushed? Is there an error log on attempted startup or for any of the cron files? Did you update the path to the cron jobs on your server (I.e. not http_server/cron anymore)?

**Comment by EternalUF** [comment]
Indeed it has, thank you!!! @jacob-grahn

**Comment by bls1999** [comment]
👍
