### ISSUE TITLE
Pr2’s Mail Server

### ISSUE THREAD

**Issue by EternalUF** [jacob-grahn/platform-racing-2-server#527]
Seems like this is down.. Breaking Forgot Password, changing email, changing guild leader through bls’ php, and etc. Anything that requires a confirmation email.

**Comment by bls1999** [comment]
@jacob-grahn urgent!

**Comment by EternalUF** [comment]
Super duper urgent!!

**Comment by BrokenBulb78** [comment]
@jacob-grahn ultra super duper urgent!!

**Comment by EternalUF** [comment]
@jacob-grahn Mega ultra super duper urgent!!

**Comment by jacob-grahn** [comment]
I think this should be resolved now. Can anyone confirm?

**Comment by EternalUF** [comment]
Confirmed!! Thank you so so so so much! @jacob-grahn
