### ISSUE TITLE
Can't exit level editor on guest account

### ISSUE THREAD

**Issue by fourst4r** [jacob-grahn/platform-racing-2-server#530]
You are prevented from exiting the level editor on a guest account by the following message: `Error: Direct logins to guest accounts are not permitted. To play as a guest, click the "Play as Guest" button on the main menu.`

**Comment by bls1999** [comment]
oh crap. I'll take a look at this tomorrow. Good catch. :+1:

**Comment by bls1999** [comment]
Should be fixed with the new additions to #524
