### ISSUE TITLE
[Urgent] VoM Issue

### ISSUE THREAD

**Issue by Pr2Colind** [jacob-grahn/platform-racing-2-server#533]
Today at 10/7/2018 I went on Kong and decided to buy a 1 month private server for the guild. When trying to buy it there was a pop-up that said this; http://prntscr.com/l33zwj so I went to my PM from Kong and it says this; http://prntscr.com/l33zg7

**Comment by Pr2Colind** [comment]
Re-opening this since the VoM got broken again, will close when the issue gets fix.

**Comment by bls1999** [comment]
@PR2Colind what error do you get?

**Comment by AshleyJ14** [comment]
I'm getting the same error when trying to buy a private server. @bls1999 the error says "could not contact the game server to finalize your order" and the kreds keep refunding into the account

**Comment by bls1999** [comment]
@jacob-grahn I can't debug this because I don't know what data is sent to/from Kong. If you can post a sample of the data sent both ways, I can debug this in the future.

**Comment by EternalUF** [comment]
Close this @Pr2Colind
