### ISSUE TITLE
guilds_top.php parses html in guild names

### ISSUE THREAD

**Issue by bls1999** [jacob-grahn/platform-racing-2-server#59]
`htmlspecialchars()` needs to be put in somewhere in that file, although I'm not quite sure where.

**Comment by Antonhs30000** [comment]
I think I fixed it, look at pull requests. @bls1999

**Comment by bls1999** [comment]
@Antonhs30000 don't think that fixed it; see my reply.

**Comment by Myst1cZ** [comment]
@bls1999 Just recently added another kind of fix for it at https://github.com/jacob-grahn/platform-racing-2-server/pull/63
