### ISSUE TITLE
Forgot Password

### ISSUE THREAD

**Issue by Negbu** [jacob-grahn/platform-racing-2-server#605]
Requesting a password to @msn.com, @hotmail.co.uk, and @live.com does not work. 

I do not receive the password in my emails.

**Comment by EternalUF** [comment]
You’ll need to make a request at Jiggmin2.com/aam.

**Comment by bls1999** [comment]
@jacob-grahn sorry to bother you, but I can't fix this-- this needs to be done in your domain registrar's control panel. Zach sent at least one and I sent two messages (January 2 w/ subj: "[Follow-Up] URGENT: Emails undeliverable to hotmail/outlook/live addresses" and May 13 w/ subj: "URL Redirect jiggmin.com and pr2hub.com MX Records") regarding this issue. The second one gives more useful information than the first. It should take about 20 mins at most to fix.

**Comment by jacob-grahn** [comment]
Ok, I updated the email settings to go through pr2hub.com instead of platformracing.com. In theory, hotmail will be happier with us now

**Comment by bls1999** [comment]
Hey @jacob-grahn, thanks for doing this. Unfortunately, that didn't work. I forwarded one of my emails on the subject back to you so you could have all the details.

**Comment by bls1999** [comment]
Hey @jacob-grahn, thanks for doing this. Unfortunately, that didn't work. I forwarded one of my emails on the subject back to you so you could have all the details readily accessible.

**Comment by bls1999** [comment]
This is fixed! Thanks again, @jacob-grahn!!
