### ISSUE TITLE
/clear

### ISSUE THREAD

**Issue by bls1999** [jacob-grahn/platform-racing-2-server#61]
I wonder if the clear function (linked below) could be replaced with something like this:

```
$this->chat_array = NULL;
__construct($chat_room_name);
```

Right now, all the /clear command does is nuke the chat.  I'm hoping that executing that command in the future can just reset the chatroom as if it was created for the first time; with the welcome message at the top and no other messages.

https://github.com/jacob-grahn/platform-racing-2-server/blob/1b0c22cd05d17450a973d6fe4f9d2c7aff38a655/server/rooms/ChatRoom.php#L24

**Comment by jacob-grahn** [comment]
That would clear data on the server. The server would then need to send a command to the clients to tell them to clear as well. I'm not able to change the client at the moment though, so we're out of luck there.

**Comment by bls1999** [comment]
Aw, rats. Thanks anyway!
