### ISSUE TITLE
making an exp limit per day?

### ISSUE THREAD

**Issue by famelegend1** [jacob-grahn/platform-racing-2-server#627]
to cut down on botting, i thought about making an exp limit per day of 2 million. it seems logical since it seems impossible to get over that amount even with max HHs and high ranks.

i can't find a variable in game.php that tracks the total amount of exp that someone gets in a day. any ideas here? ty.

**Comment by bls1999** [comment]
Player.php has the `exp_today` property. I wouldn't have a problem capping that at something a little less than the impossible amount per day to try to limit the advantages gained by exp farming.
