### ISSUE TITLE
Kong client is broken

### ISSUE THREAD

**Issue by bls1999** [jacob-grahn/platform-racing-2-server#64]
For some reason the game is now requesting http://cdn.jiggmin.com/crossdomain.xml, but only from that client.  Could the server move have messed with the security settings for Kongregate?

**Comment by jacob-grahn** [comment]
Well that's odd. It looks like cdn.jiggmin.com was pointing to the ip of the old server, so I changed it to the new server! For whatever reason Kong is telling my to install a flash player even though I already have one, so someone else will need to check if this is working.

**Comment by Antonhs30000** [comment]
It works for me. You have to click **Allow Flash**. 😄 @jacob-grahn 

**Chrome**
![image](https://user-images.githubusercontent.com/35195062/35181494-601ec8b0-fdcb-11e7-8518-becaed8a7841.png)

**Firefox**
![image](https://user-images.githubusercontent.com/35195062/35181502-839e107a-fdcb-11e7-8c12-336f99a54a73.png)

**Microsoft Edge**
![image](https://user-images.githubusercontent.com/35195062/35181507-96ebaf70-fdcb-11e7-8919-b99aaef35fe0.png)
