### ISSUE TITLE
Help me recovering my account, please

### ISSUE THREAD

**Issue by HopeKobayashi** [jacob-grahn/platform-racing-2-server#644]
Hi, as the title says I lost my account.
I used to play this game almost 11-10 years ago and my nickname was "alan517", I tried to login but it says that my account doesn't exist.

I've created a new account and searched alan517, and found my levels
https://ibb.co/xj7Q6rg

There is the profile

If you want something to prove that thats my account, I still remember the email, I'm not sure if I remember the password, but I still have my email,  I can confirm everything

Thank you so much, goodnight!
![alan517](https://user-images.githubusercontent.com/63700483/79307766-08379300-7ebd-11ea-8079-ff3bbe281c30.png)

**Comment by EternalUF** [comment]
Howdy! We are currently channeling account recovery requests through Jiggmin2.com/aam if you could please head over there I’d be able to assist.

**Comment by bls1999** [comment]
Please visit the [Ask a Mod forum](https://jiggmin2.com/aam) on [Jiggmin's Village](https://jiggmin2.com/forums) to request an account recovery.
