### ISSUE TITLE
Socket command for confirm window?

### ISSUE THREAD

**Issue by bls1999** [jacob-grahn/platform-racing-2-server#68]
@jacob-grahn 

Is there a command that the socket server can send to the client to ask a user if they're sure they want to perform an action?

For instance, ``$player->write('message`hello world!')`` sends the player a message popup that says "hello world!".  Could I theoretically replace ``message` `` with ``confirm` `` or something similar to pop up a confirmation?

**Comment by jacob-grahn** [comment]
Nope, not without being able to edit the client.

**Comment by bls1999** [comment]
Gotcha. Thanks!
