### ISSUE TITLE
Editing and lifting ban

### ISSUE THREAD

**Issue by EternalUF** [jacob-grahn/platform-racing-2-server#73]
When trying to edit or lift bans the page returns "File not found"

**Comment by woodenstix** [comment]
Why would you edit and lift bans in the first place

**Comment by Antonhs30000** [comment]
I assume Jiggmin edited the file name or moved it to another folder? @EternalUF

**Comment by bls1999** [comment]
Nah, he forgot to add /mod or /bans to the start of the URLs when he was removing the http hardcoding from
a bunch of files.  Also, it's a new server, so there's bound to be some configuration issues.

**Comment by jacob-grahn** [comment]
It looks like bls got this one fixed :)
