### ISSUE TITLE
Forgot password and email changing

### ISSUE THREAD

**Issue by EternalUF** [jacob-grahn/platform-racing-2-server#77]
Trying to do forgot password returns an Error 2032, and trying to change your email returns an Error 500

**Comment by Antonhs30000** [comment]
Error 2032: There was an unknown error.
Error 500: Internal server error.

I think you're getting these errors cause of the DDoS. So I think you need to be patient. 😃

**Comment by woodenstix** [comment]
>I think you're getting these errors cause of the DDoS. So I think you need to be patient. 😃

There was no ddos yesterday

**Comment by Antonhs30000** [comment]
¯\_(ツ)_/¯

**Comment by bls1999** [comment]
As far as I can tell, @Myst1cZ has stopped DDoSing the servers.  The issue seems to be with @jacob-grahn's new server config.

**Comment by jacob-grahn** [comment]
I needed to install the Mail pear package for the server to be able to send emails. This should be working now.
