### ISSUE TITLE
Email changing issue

### ISSUE THREAD

**Issue by EternalUF** [jacob-grahn/platform-racing-2-server#82]
There seems to be an issue with email storage, we are receiving several complaints that the email people are typing is saving with changed characters.

**Comment by EternalUF** [comment]
"." is changing to "/" for example.

**Comment by woodenstix** [comment]
i cant change bls email to mine because of this, pls fix

**Comment by bls1999** [comment]
Just got home; I'll look into some of the recent changes and see if I can find what's causing the problem.  It may be something that wasn't changed in the code.

**Comment by jacob-grahn** [comment]
Well this sounds very odd. I don't have time to look into it tonight, but I'll check out as soon as I can.

**Comment by bls1999** [comment]
I investigated it further and I have absolutely no idea what's causing this issue.  As far as I know, there's no code that would mess with the third character of each email address.  Could it be a hashing/encoding issue?

**Comment by jacob-grahn** [comment]
Is this working now? I had mis-typed the number '1' with a lowercase 'l' in the $CHANGE_EMAIL_IV environment variable.

**Comment by EternalUF** [comment]
I’m currently in class, but according to a fellow staff member it seems to be working! When I get some free time in a bit I’ll do some additional testing and close this issue if all seems good! Thank you!

**Comment by EternalUF** [comment]
This is working! :D
