### ISSUE TITLE
Pr2 Level editor Drawing

### ISSUE THREAD

**Issue by a7x3** [jacob-grahn/platform-racing-2-server#84]
Hey Jiggy, long time no see

I was just curious, Is there any way that the level doesn't have to draw all of you're old art work before drawing the new? I've noticed it on Blacklight 2, you have to sit there for ages to let all the old artwork draw away before getting too the current stuff.

Obviously I don't expect this to be at the top of your priority list, but if it's possible, maybe make it a feature in PRF if it's able to be done?

**Comment by bls1999** [comment]
I recall somewhere down the line Jiggy saying that he's going to make level backgrounds load as one big image.  That could've changed since then, but just thought I'd throw that piece of information into the pot.

**Comment by jacob-grahn** [comment]
This definitely isn't a problem that I intend to fix for PR2, but there are things we can do better for future games. Probably something like having checkpoint images that are created when a level is saved, and then any future edits start from that checkpoint, rather than the beginning of time.
