### ISSUE TITLE
@Jacob README: Organizing Issues and Pull Requests

### ISSUE THREAD

**Issue by bls1999** [jacob-grahn/platform-racing-2-server#93]
Hey @jacob-grahn, just gonna leave an organized list of existing issues/pull requests/to-dos here:

(!!) = Quick merge/fix

 - To-Do: Convert all DB queries to PDO.
 - #308, which fixes a ton of http_server errors
 - #299, which provides a potential fix for guests not earning Kong badges, fah, and other things
 - Add botting prevention as outlined in #285.

Can be closed:
 - #247 
 - #256 
 - #283 

Hopefully this helps organize everything! I'll update it as we go.

**Comment by woodenstix** [comment]
how about we talk about maps with passwords required you can't get on them lol
