### ISSUE TITLE
Admin Tool Broken

### ISSUE THREAD

**Issue by bls1999** [jacob-grahn/platform-racing-2-server#97]
When trying to update accounts, we get this:

`error=Incorrect number of arguments for PROCEDURE jiggmin_games.user_update; expected 11, got 12`

I think this may be because you didn't add guild_id to the list of arguments for user_update.  That's the key to getting my edits to work.

**Comment by jacob-grahn** [comment]
Give it a try now

**Comment by bls1999** [comment]
It's changing the guild ID to the player ID.  @jacob-grahn check my definition for $guild_id in update_account.php.  This was an error I made in update_guild.php as well.

**Comment by bls1999** [comment]
@jacob-grahn my fixes are in #98
